api:
  param:
    validate: true
server:
  port: 6001
spring:
  #时间格式的统一处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jta:
    log-dir: "d:/logs/"
  redis:
    # host: 172.168.252.221
    host: 172.168.250.92
    port: 10008
    timeout: 60000
    database: 13
    password: root

logging:
  level:
    com.zfsoft: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  cache:
    timeout: 360
debug: true

log:
  extend:
    fields: true

#jasypt加密时的salt值
jasypt:
  encryptor:
    password: zfsoft888
