package com.zfsoft.superwindow.data.clzs;

import lombok.Data;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * @author: liangss
 * @create: 2020-11-07 16:46:59
 * @description: 识别模板区块
 */
@Data
public class FaModelTemplateBlock {

    /* 主键  */
    @NotNull(message = "id不能为空")
    private Long id;

    /*  识别模板区块业务主键 */
    private String faModelTemplateBlockOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.FA_MODEL_TEMPLATE_OID
     *
     * @mbggenerated
     */
    private String faModelTemplateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.MATERIAL_CATALOG_OID
     *
     * @mbggenerated
     */
    private String materialCatalogElementOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.FA_MODEL_TEMPLATE_NAME
     *
     * @mbggenerated
     */
    private String faModelTemplateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.BLOCK_NAME
     *
     * @mbggenerated
     */
    private String blockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.BLOCK_CODE
     *
     * @mbggenerated
     */
    private String blockCode;

    /**
     * 识别类型(1-印刷、2-手写、3-图像、4-特征块)
     */
    private String recognitionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.HEIGHT
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.WIDTH
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.X
     *
     * @mbggenerated
     */
    private Integer x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.Y
     *
     * @mbggenerated
     */
    private Integer y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.MARQUEE_VALUE
     *
     * @mbggenerated
     */
    private String marqueeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.MARQUEE_JSON_VALUE
     *
     * @mbggenerated
     */
    private String marqueeJsonValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fa_model_template_block.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /*  创建时间 */
    private Date createDate;

    /*  修改时间  */
    private Date modifyDate;

    /* 逻辑删除状态 0 未删除 1 删除  */
    private Integer delFlag;

    private MaterialCatalog materialCatalog;
    private FaModelTemplate faModelTemplate;

}
