package com.zfsoft.single.dbaccess.data.ywbl;

import java.util.Date;

public class DbInternetAuditRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.RECORD_OID
     *
     * @mbggenerated
     */
    private String recordOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.CASE_OID
     *
     * @mbggenerated
     */
    private String caseOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.AUDIT_RESULT
     *
     * @mbggenerated
     */
    private String auditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.RESULT_DESC
     *
     * @mbggenerated
     */
    private String resultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internet_audit_record.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.ID
     *
     * @return the value of t_internet_audit_record.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.ID
     *
     * @param id the value for t_internet_audit_record.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.RECORD_OID
     *
     * @return the value of t_internet_audit_record.RECORD_OID
     *
     * @mbggenerated
     */
    public String getRecordOid() {
        return recordOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.RECORD_OID
     *
     * @param recordOid the value for t_internet_audit_record.RECORD_OID
     *
     * @mbggenerated
     */
    public void setRecordOid(String recordOid) {
        this.recordOid = recordOid == null ? null : recordOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.CASE_OID
     *
     * @return the value of t_internet_audit_record.CASE_OID
     *
     * @mbggenerated
     */
    public String getCaseOid() {
        return caseOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.CASE_OID
     *
     * @param caseOid the value for t_internet_audit_record.CASE_OID
     *
     * @mbggenerated
     */
    public void setCaseOid(String caseOid) {
        this.caseOid = caseOid == null ? null : caseOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.AUDIT_RESULT
     *
     * @return the value of t_internet_audit_record.AUDIT_RESULT
     *
     * @mbggenerated
     */
    public String getAuditResult() {
        return auditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.AUDIT_RESULT
     *
     * @param auditResult the value for t_internet_audit_record.AUDIT_RESULT
     *
     * @mbggenerated
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult == null ? null : auditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.RESULT_DESC
     *
     * @return the value of t_internet_audit_record.RESULT_DESC
     *
     * @mbggenerated
     */
    public String getResultDesc() {
        return resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.RESULT_DESC
     *
     * @param resultDesc the value for t_internet_audit_record.RESULT_DESC
     *
     * @mbggenerated
     */
    public void setResultDesc(String resultDesc) {
        this.resultDesc = resultDesc == null ? null : resultDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.CREATE_DATE
     *
     * @return the value of t_internet_audit_record.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.CREATE_DATE
     *
     * @param createDate the value for t_internet_audit_record.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.CREATE_USER
     *
     * @return the value of t_internet_audit_record.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.CREATE_USER
     *
     * @param createUser the value for t_internet_audit_record.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internet_audit_record.MODIFY_DATE
     *
     * @return the value of t_internet_audit_record.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internet_audit_record.MODIFY_DATE
     *
     * @param modifyDate the value for t_internet_audit_record.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}