package com.zfsoft.service.dbaccess.data.sxService;

import java.util.Date;

public class DbReviewPoints {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.OID
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.REFINED_MATERIAL_OID
     *
     * @mbggenerated
     */
    private String refinedMaterialOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.REVIEW_POINTS
     *
     * @mbggenerated
     */
    private String reviewPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.SERIAL_NUMBER
     *
     * @mbggenerated
     */
    private Long serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review_points.DELETE_STATUS
     *
     * @mbggenerated
     */
    private Short deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.ID
     *
     * @return the value of t_review_points.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.ID
     *
     * @param id the value for t_review_points.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.OID
     *
     * @return the value of t_review_points.OID
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.OID
     *
     * @param oid the value for t_review_points.OID
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.REFINED_MATERIAL_OID
     *
     * @return the value of t_review_points.REFINED_MATERIAL_OID
     *
     * @mbggenerated
     */
    public String getRefinedMaterialOid() {
        return refinedMaterialOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.REFINED_MATERIAL_OID
     *
     * @param refinedMaterialOid the value for t_review_points.REFINED_MATERIAL_OID
     *
     * @mbggenerated
     */
    public void setRefinedMaterialOid(String refinedMaterialOid) {
        this.refinedMaterialOid = refinedMaterialOid == null ? null : refinedMaterialOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.REVIEW_POINTS
     *
     * @return the value of t_review_points.REVIEW_POINTS
     *
     * @mbggenerated
     */
    public String getReviewPoints() {
        return reviewPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.REVIEW_POINTS
     *
     * @param reviewPoints the value for t_review_points.REVIEW_POINTS
     *
     * @mbggenerated
     */
    public void setReviewPoints(String reviewPoints) {
        this.reviewPoints = reviewPoints == null ? null : reviewPoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.SERIAL_NUMBER
     *
     * @return the value of t_review_points.SERIAL_NUMBER
     *
     * @mbggenerated
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.SERIAL_NUMBER
     *
     * @param serialNumber the value for t_review_points.SERIAL_NUMBER
     *
     * @mbggenerated
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.CREATE_DATE
     *
     * @return the value of t_review_points.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.CREATE_DATE
     *
     * @param createDate the value for t_review_points.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.MODIFY_DATE
     *
     * @return the value of t_review_points.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.MODIFY_DATE
     *
     * @param modifyDate the value for t_review_points.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review_points.DELETE_STATUS
     *
     * @return the value of t_review_points.DELETE_STATUS
     *
     * @mbggenerated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review_points.DELETE_STATUS
     *
     * @param deleteStatus the value for t_review_points.DELETE_STATUS
     *
     * @mbggenerated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}