package com.zfsoft.service.dbaccess.data.sxService;

import java.util.Date;

public class DbSxMaterialFormTemp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.OID
     *
     * @mbg.generated
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.MATERIAL_OID
     *
     * @mbg.generated
     */
    private String materialOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.SERVICE_OID
     *
     * @mbg.generated
     */
    private String serviceOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.FORM_CODE
     *
     * @mbg.generated
     */
    private String formCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.TEMPLATE_OID
     *
     * @mbg.generated
     */
    private String templateOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.TEMPLATE_NAME
     *
     * @mbg.generated
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.DEL_FLAG
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.MODIFY_DATE
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.SEAL_URL
     *
     * @mbg.generated
     */
    private String sealUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.TEMPLATE_URL
     *
     * @mbg.generated
     */
    private String templateUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.SEAL_STATUS
     *
     * @mbg.generated
     */
    private Integer sealStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.DESIGN_OID
     *
     * @mbg.generated
     */
    private String designOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.MADE_MATERIAL_TYPE
     *
     * @mbg.generated
     */
    private String madeMaterialType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.MATERIAL_NAME
     *
     * @mbg.generated
     */
    private String materialName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.ID
     *
     * @return the value of t_sx_material_form_template.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.ID
     *
     * @param id the value for t_sx_material_form_template.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.OID
     *
     * @return the value of t_sx_material_form_template.OID
     *
     * @mbg.generated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.OID
     *
     * @param oid the value for t_sx_material_form_template.OID
     *
     * @mbg.generated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.MATERIAL_OID
     *
     * @return the value of t_sx_material_form_template.MATERIAL_OID
     *
     * @mbg.generated
     */
    public String getMaterialOid() {
        return materialOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.MATERIAL_OID
     *
     * @param materialOid the value for t_sx_material_form_template.MATERIAL_OID
     *
     * @mbg.generated
     */
    public void setMaterialOid(String materialOid) {
        this.materialOid = materialOid == null ? null : materialOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.SERVICE_OID
     *
     * @return the value of t_sx_material_form_template.SERVICE_OID
     *
     * @mbg.generated
     */
    public String getServiceOid() {
        return serviceOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.SERVICE_OID
     *
     * @param serviceOid the value for t_sx_material_form_template.SERVICE_OID
     *
     * @mbg.generated
     */
    public void setServiceOid(String serviceOid) {
        this.serviceOid = serviceOid == null ? null : serviceOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.FORM_CODE
     *
     * @return the value of t_sx_material_form_template.FORM_CODE
     *
     * @mbg.generated
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.FORM_CODE
     *
     * @param formCode the value for t_sx_material_form_template.FORM_CODE
     *
     * @mbg.generated
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode == null ? null : formCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.TEMPLATE_OID
     *
     * @return the value of t_sx_material_form_template.TEMPLATE_OID
     *
     * @mbg.generated
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.TEMPLATE_OID
     *
     * @param templateOid the value for t_sx_material_form_template.TEMPLATE_OID
     *
     * @mbg.generated
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid == null ? null : templateOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.TEMPLATE_NAME
     *
     * @return the value of t_sx_material_form_template.TEMPLATE_NAME
     *
     * @mbg.generated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.TEMPLATE_NAME
     *
     * @param templateName the value for t_sx_material_form_template.TEMPLATE_NAME
     *
     * @mbg.generated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.DEL_FLAG
     *
     * @return the value of t_sx_material_form_template.DEL_FLAG
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.DEL_FLAG
     *
     * @param delFlag the value for t_sx_material_form_template.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.CREATE_DATE
     *
     * @return the value of t_sx_material_form_template.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.CREATE_DATE
     *
     * @param createDate the value for t_sx_material_form_template.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.MODIFY_DATE
     *
     * @return the value of t_sx_material_form_template.MODIFY_DATE
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.MODIFY_DATE
     *
     * @param modifyDate the value for t_sx_material_form_template.MODIFY_DATE
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.SEAL_URL
     *
     * @return the value of t_sx_material_form_template.SEAL_URL
     *
     * @mbg.generated
     */
    public String getSealUrl() {
        return sealUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.SEAL_URL
     *
     * @param sealUrl the value for t_sx_material_form_template.SEAL_URL
     *
     * @mbg.generated
     */
    public void setSealUrl(String sealUrl) {
        this.sealUrl = sealUrl == null ? null : sealUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.TEMPLATE_URL
     *
     * @return the value of t_sx_material_form_template.TEMPLATE_URL
     *
     * @mbg.generated
     */
    public String getTemplateUrl() {
        return templateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.TEMPLATE_URL
     *
     * @param templateUrl the value for t_sx_material_form_template.TEMPLATE_URL
     *
     * @mbg.generated
     */
    public void setTemplateUrl(String templateUrl) {
        this.templateUrl = templateUrl == null ? null : templateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.SEAL_STATUS
     *
     * @return the value of t_sx_material_form_template.SEAL_STATUS
     *
     * @mbg.generated
     */
    public Integer getSealStatus() {
        return sealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.SEAL_STATUS
     *
     * @param sealStatus the value for t_sx_material_form_template.SEAL_STATUS
     *
     * @mbg.generated
     */
    public void setSealStatus(Integer sealStatus) {
        this.sealStatus = sealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.DESIGN_OID
     *
     * @return the value of t_sx_material_form_template.DESIGN_OID
     *
     * @mbg.generated
     */
    public String getDesignOid() {
        return designOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.DESIGN_OID
     *
     * @param designOid the value for t_sx_material_form_template.DESIGN_OID
     *
     * @mbg.generated
     */
    public void setDesignOid(String designOid) {
        this.designOid = designOid == null ? null : designOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.MADE_MATERIAL_TYPE
     *
     * @return the value of t_sx_material_form_template.MADE_MATERIAL_TYPE
     *
     * @mbg.generated
     */
    public String getMadeMaterialType() {
        return madeMaterialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.MADE_MATERIAL_TYPE
     *
     * @param madeMaterialType the value for t_sx_material_form_template.MADE_MATERIAL_TYPE
     *
     * @mbg.generated
     */
    public void setMadeMaterialType(String madeMaterialType) {
        this.madeMaterialType = madeMaterialType == null ? null : madeMaterialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_form_template.MATERIAL_NAME
     *
     * @return the value of t_sx_material_form_template.MATERIAL_NAME
     *
     * @mbg.generated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_form_template.MATERIAL_NAME
     *
     * @param materialName the value for t_sx_material_form_template.MATERIAL_NAME
     *
     * @mbg.generated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }
}