package com.zfsoft.service.dbaccess.data.sxService;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DbSxFieldTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public DbSxFieldTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidIsNull() {
            addCriterion("FIELD_TYPE_OID is null");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidIsNotNull() {
            addCriterion("FIELD_TYPE_OID is not null");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidEqualTo(String value) {
            addCriterion("FIELD_TYPE_OID =", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidNotEqualTo(String value) {
            addCriterion("FIELD_TYPE_OID <>", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidGreaterThan(String value) {
            addCriterion("FIELD_TYPE_OID >", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_TYPE_OID >=", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidLessThan(String value) {
            addCriterion("FIELD_TYPE_OID <", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidLessThanOrEqualTo(String value) {
            addCriterion("FIELD_TYPE_OID <=", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidLike(String value) {
            addCriterion("FIELD_TYPE_OID like", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidNotLike(String value) {
            addCriterion("FIELD_TYPE_OID not like", value, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidIn(List<String> values) {
            addCriterion("FIELD_TYPE_OID in", values, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidNotIn(List<String> values) {
            addCriterion("FIELD_TYPE_OID not in", values, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidBetween(String value1, String value2) {
            addCriterion("FIELD_TYPE_OID between", value1, value2, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeOidNotBetween(String value1, String value2) {
            addCriterion("FIELD_TYPE_OID not between", value1, value2, "fieldTypeOid");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameIsNull() {
            addCriterion("FIELD_TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameIsNotNull() {
            addCriterion("FIELD_TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameEqualTo(String value) {
            addCriterion("FIELD_TYPE_NAME =", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameNotEqualTo(String value) {
            addCriterion("FIELD_TYPE_NAME <>", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameGreaterThan(String value) {
            addCriterion("FIELD_TYPE_NAME >", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_TYPE_NAME >=", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameLessThan(String value) {
            addCriterion("FIELD_TYPE_NAME <", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameLessThanOrEqualTo(String value) {
            addCriterion("FIELD_TYPE_NAME <=", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameLike(String value) {
            addCriterion("FIELD_TYPE_NAME like", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameNotLike(String value) {
            addCriterion("FIELD_TYPE_NAME not like", value, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameIn(List<String> values) {
            addCriterion("FIELD_TYPE_NAME in", values, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameNotIn(List<String> values) {
            addCriterion("FIELD_TYPE_NAME not in", values, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameBetween(String value1, String value2) {
            addCriterion("FIELD_TYPE_NAME between", value1, value2, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andFieldTypeNameNotBetween(String value1, String value2) {
            addCriterion("FIELD_TYPE_NAME not between", value1, value2, "fieldTypeName");
            return (Criteria) this;
        }

        public Criteria andParentOidIsNull() {
            addCriterion("PARENT_OID is null");
            return (Criteria) this;
        }

        public Criteria andParentOidIsNotNull() {
            addCriterion("PARENT_OID is not null");
            return (Criteria) this;
        }

        public Criteria andParentOidEqualTo(String value) {
            addCriterion("PARENT_OID =", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotEqualTo(String value) {
            addCriterion("PARENT_OID <>", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidGreaterThan(String value) {
            addCriterion("PARENT_OID >", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_OID >=", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidLessThan(String value) {
            addCriterion("PARENT_OID <", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidLessThanOrEqualTo(String value) {
            addCriterion("PARENT_OID <=", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidLike(String value) {
            addCriterion("PARENT_OID like", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotLike(String value) {
            addCriterion("PARENT_OID not like", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidIn(List<String> values) {
            addCriterion("PARENT_OID in", values, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotIn(List<String> values) {
            addCriterion("PARENT_OID not in", values, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidBetween(String value1, String value2) {
            addCriterion("PARENT_OID between", value1, value2, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotBetween(String value1, String value2) {
            addCriterion("PARENT_OID not between", value1, value2, "parentOid");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryIsNull() {
            addCriterion("CHANGE_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryIsNotNull() {
            addCriterion("CHANGE_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryEqualTo(Integer value) {
            addCriterion("CHANGE_CATEGORY =", value, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryNotEqualTo(Integer value) {
            addCriterion("CHANGE_CATEGORY <>", value, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryGreaterThan(Integer value) {
            addCriterion("CHANGE_CATEGORY >", value, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("CHANGE_CATEGORY >=", value, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryLessThan(Integer value) {
            addCriterion("CHANGE_CATEGORY <", value, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryLessThanOrEqualTo(Integer value) {
            addCriterion("CHANGE_CATEGORY <=", value, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryIn(List<Integer> values) {
            addCriterion("CHANGE_CATEGORY in", values, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryNotIn(List<Integer> values) {
            addCriterion("CHANGE_CATEGORY not in", values, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryBetween(Integer value1, Integer value2) {
            addCriterion("CHANGE_CATEGORY between", value1, value2, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andChangeCategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("CHANGE_CATEGORY not between", value1, value2, "changeCategory");
            return (Criteria) this;
        }

        public Criteria andTableStatusIsNull() {
            addCriterion("TABLE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTableStatusIsNotNull() {
            addCriterion("TABLE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTableStatusEqualTo(Integer value) {
            addCriterion("TABLE_STATUS =", value, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusNotEqualTo(Integer value) {
            addCriterion("TABLE_STATUS <>", value, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusGreaterThan(Integer value) {
            addCriterion("TABLE_STATUS >", value, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("TABLE_STATUS >=", value, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusLessThan(Integer value) {
            addCriterion("TABLE_STATUS <", value, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusLessThanOrEqualTo(Integer value) {
            addCriterion("TABLE_STATUS <=", value, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusIn(List<Integer> values) {
            addCriterion("TABLE_STATUS in", values, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusNotIn(List<Integer> values) {
            addCriterion("TABLE_STATUS not in", values, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusBetween(Integer value1, Integer value2) {
            addCriterion("TABLE_STATUS between", value1, value2, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andTableStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("TABLE_STATUS not between", value1, value2, "tableStatus");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("SORT is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("SORT =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("SORT <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("SORT >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("SORT <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("SORT <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("SORT in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("SORT not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("SORT between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("LEVEL =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("LEVEL <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("LEVEL >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("LEVEL >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("LEVEL <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("LEVEL <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("LEVEL like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("LEVEL not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("LEVEL in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("LEVEL not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("LEVEL between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("LEVEL not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIsAbleIsNull() {
            addCriterion("IS_ABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsAbleIsNotNull() {
            addCriterion("IS_ABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsAbleEqualTo(Integer value) {
            addCriterion("IS_ABLE =", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleNotEqualTo(Integer value) {
            addCriterion("IS_ABLE <>", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleGreaterThan(Integer value) {
            addCriterion("IS_ABLE >", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_ABLE >=", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleLessThan(Integer value) {
            addCriterion("IS_ABLE <", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleLessThanOrEqualTo(Integer value) {
            addCriterion("IS_ABLE <=", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleIn(List<Integer> values) {
            addCriterion("IS_ABLE in", values, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleNotIn(List<Integer> values) {
            addCriterion("IS_ABLE not in", values, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleBetween(Integer value1, Integer value2) {
            addCriterion("IS_ABLE between", value1, value2, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_ABLE not between", value1, value2, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidIsNull() {
            addCriterion("CREATE_USER_OID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidIsNotNull() {
            addCriterion("CREATE_USER_OID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidEqualTo(String value) {
            addCriterion("CREATE_USER_OID =", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidNotEqualTo(String value) {
            addCriterion("CREATE_USER_OID <>", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidGreaterThan(String value) {
            addCriterion("CREATE_USER_OID >", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_OID >=", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidLessThan(String value) {
            addCriterion("CREATE_USER_OID <", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_OID <=", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidLike(String value) {
            addCriterion("CREATE_USER_OID like", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidNotLike(String value) {
            addCriterion("CREATE_USER_OID not like", value, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidIn(List<String> values) {
            addCriterion("CREATE_USER_OID in", values, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidNotIn(List<String> values) {
            addCriterion("CREATE_USER_OID not in", values, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidBetween(String value1, String value2) {
            addCriterion("CREATE_USER_OID between", value1, value2, "createUserOid");
            return (Criteria) this;
        }

        public Criteria andCreateUserOidNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_OID not between", value1, value2, "createUserOid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sx_field_type
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sx_field_type
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
