server:
  port: 8088
spring:
  codec:
    max-in-memory-size: 2MB
  redis:
    host: 172.21.176.204
    port: 13302
    timeout: 60000
    database: 13
    password: ZhuoFan888!@#
    lettuce:
      shutdown-timeout: 100
  cloud:
    gateway:
      enabled:
      discovery:
        locator:
          enabled: true
      routes:
        - id: platform-service-provider
          uri: lb://platform-service-provider
          predicates:
            - Path=/platform/**
          filters:
            - StripPrefix=1
        - id: settings-service-provider
          uri: lb://settings-service-provider
          predicates:
            - Path=/settings/**
          filters:
            - StripPrefix=1
        - id: workflow-service-provider
          uri: lb://workflow-service-provider
          predicates:
            - Path=/workflow/**
          filters:
            - StripPrefix=1
        - id: form-service-provider
          uri: lb://form-service-provider
          predicates:
            - Path=/form/**
          filters:
            - StripPrefix=1
        - id: zf-case-service-provider
          uri: lb://zf-case-service-provider
          predicates:
            - Path=/case-service/**
          filters:
            - StripPrefix=1
kaptcha:
  border:
    style: "no"
    color: "105,179,90"
  image:
    width: 250
    height: 90
  session:
    key: "code"
  textproducer:
    char:
      length: 4
      string: "0123456789"
    font:
      names: "宋体,楷体,微软雅黑"
      size: 70
      color: "red"
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
client:
  feign:
    global:
      error:
        handler: true
feign:
  httpclient:
    max-connections: 800
    max-connections-per-route: 300
    time-to-live: 9000
  sentinel:
    enabled: true

#jasypt加密时的salt值
jasypt:
  encryptor:
    password: zfsoft888

com:
  zfsoft:
    #验证站点请求是否开启 true开启（默认）  false关闭
    refererCheck: false
    #验证站点请求来源，用于跨站点请求伪造 设置可访问的IP
    allowSites: localhost,127.0.0.1,172.168.252.121,122.112.225.220,172.21.178.38
    login:
      validCode: false
    #访问的限制字符 如 "*,&"
    limitChars:
    # 权限不拦截列表 多个使用 , 号隔开
    security:
      access: "/ueditor/controller,/case-service/ha/**,/case-service//ha/**,/form/manager/**"
ribbon:
  ConnectTimeout: 60000 #连接超时时间(ms)
  ReadTimeout: 60000 #通信超时时间(ms)

# 日志配置
logging:
  config: classpath:logback-logstash.xml
log:
  level: info
  path: logs/
logstash:
  server-addr: 122.112.225.220:9601
zfsoft:
  feign:
    settings: settings-service-provider
