package com.zfsoft.superwindow.dbaccess.data;

import java.util.Date;

public class DbAfterAdvisory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.AFTER_ADVISORY_OID
     *
     * @mbggenerated
     */
    private String afterAdvisoryOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.REPLY_USER_OID
     *
     * @mbggenerated
     */
    private String replyUserOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.REPLY_ORGAN_OID
     *
     * @mbggenerated
     */
    private String replyOrganOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.ADVISORY_USER_OID
     *
     * @mbggenerated
     */
    private String advisoryUserOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.ADVISORY_TIME
     *
     * @mbggenerated
     */
    private Date advisoryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.CALL_SUBJECT_OID
     *
     * @mbggenerated
     */
    private String callSubjectOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.REPLY_STATE
     *
     * @mbggenerated
     */
    private Integer replyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_after_advisory.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.ID
     *
     * @return the value of t_after_advisory.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.ID
     *
     * @param id the value for t_after_advisory.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.AFTER_ADVISORY_OID
     *
     * @return the value of t_after_advisory.AFTER_ADVISORY_OID
     *
     * @mbggenerated
     */
    public String getAfterAdvisoryOid() {
        return afterAdvisoryOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.AFTER_ADVISORY_OID
     *
     * @param afterAdvisoryOid the value for t_after_advisory.AFTER_ADVISORY_OID
     *
     * @mbggenerated
     */
    public void setAfterAdvisoryOid(String afterAdvisoryOid) {
        this.afterAdvisoryOid = afterAdvisoryOid == null ? null : afterAdvisoryOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.SORT
     *
     * @return the value of t_after_advisory.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.SORT
     *
     * @param sort the value for t_after_advisory.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.REPLY_USER_OID
     *
     * @return the value of t_after_advisory.REPLY_USER_OID
     *
     * @mbggenerated
     */
    public String getReplyUserOid() {
        return replyUserOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.REPLY_USER_OID
     *
     * @param replyUserOid the value for t_after_advisory.REPLY_USER_OID
     *
     * @mbggenerated
     */
    public void setReplyUserOid(String replyUserOid) {
        this.replyUserOid = replyUserOid == null ? null : replyUserOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.REPLY_ORGAN_OID
     *
     * @return the value of t_after_advisory.REPLY_ORGAN_OID
     *
     * @mbggenerated
     */
    public String getReplyOrganOid() {
        return replyOrganOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.REPLY_ORGAN_OID
     *
     * @param replyOrganOid the value for t_after_advisory.REPLY_ORGAN_OID
     *
     * @mbggenerated
     */
    public void setReplyOrganOid(String replyOrganOid) {
        this.replyOrganOid = replyOrganOid == null ? null : replyOrganOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.ADVISORY_USER_OID
     *
     * @return the value of t_after_advisory.ADVISORY_USER_OID
     *
     * @mbggenerated
     */
    public String getAdvisoryUserOid() {
        return advisoryUserOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.ADVISORY_USER_OID
     *
     * @param advisoryUserOid the value for t_after_advisory.ADVISORY_USER_OID
     *
     * @mbggenerated
     */
    public void setAdvisoryUserOid(String advisoryUserOid) {
        this.advisoryUserOid = advisoryUserOid == null ? null : advisoryUserOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.ADVISORY_TIME
     *
     * @return the value of t_after_advisory.ADVISORY_TIME
     *
     * @mbggenerated
     */
    public Date getAdvisoryTime() {
        return advisoryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.ADVISORY_TIME
     *
     * @param advisoryTime the value for t_after_advisory.ADVISORY_TIME
     *
     * @mbggenerated
     */
    public void setAdvisoryTime(Date advisoryTime) {
        this.advisoryTime = advisoryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.CALL_SUBJECT_OID
     *
     * @return the value of t_after_advisory.CALL_SUBJECT_OID
     *
     * @mbggenerated
     */
    public String getCallSubjectOid() {
        return callSubjectOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.CALL_SUBJECT_OID
     *
     * @param callSubjectOid the value for t_after_advisory.CALL_SUBJECT_OID
     *
     * @mbggenerated
     */
    public void setCallSubjectOid(String callSubjectOid) {
        this.callSubjectOid = callSubjectOid == null ? null : callSubjectOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.REPLY_STATE
     *
     * @return the value of t_after_advisory.REPLY_STATE
     *
     * @mbggenerated
     */
    public Integer getReplyState() {
        return replyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.REPLY_STATE
     *
     * @param replyState the value for t_after_advisory.REPLY_STATE
     *
     * @mbggenerated
     */
    public void setReplyState(Integer replyState) {
        this.replyState = replyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.IS_DELETE
     *
     * @return the value of t_after_advisory.IS_DELETE
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.IS_DELETE
     *
     * @param isDelete the value for t_after_advisory.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.CREATE_DATE
     *
     * @return the value of t_after_advisory.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.CREATE_DATE
     *
     * @param createDate the value for t_after_advisory.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_after_advisory.MODIFY_DATE
     *
     * @return the value of t_after_advisory.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_after_advisory.MODIFY_DATE
     *
     * @param modifyDate the value for t_after_advisory.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}