package com.zfsoft.superwindow.dbaccess.data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DbFaModelTemplateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public DbFaModelTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidIsNull() {
            addCriterion("FA_MODEL_TEMPLATE_OID is null");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidIsNotNull() {
            addCriterion("FA_MODEL_TEMPLATE_OID is not null");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidEqualTo(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID =", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidNotEqualTo(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID <>", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidGreaterThan(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID >", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidGreaterThanOrEqualTo(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID >=", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidLessThan(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID <", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidLessThanOrEqualTo(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID <=", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidLike(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID like", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidNotLike(String value) {
            addCriterion("FA_MODEL_TEMPLATE_OID not like", value, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidIn(List<String> values) {
            addCriterion("FA_MODEL_TEMPLATE_OID in", values, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidNotIn(List<String> values) {
            addCriterion("FA_MODEL_TEMPLATE_OID not in", values, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidBetween(String value1, String value2) {
            addCriterion("FA_MODEL_TEMPLATE_OID between", value1, value2, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andFaModelTemplateOidNotBetween(String value1, String value2) {
            addCriterion("FA_MODEL_TEMPLATE_OID not between", value1, value2, "faModelTemplateOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidIsNull() {
            addCriterion("MATERIAL_CATALOG_OID is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidIsNotNull() {
            addCriterion("MATERIAL_CATALOG_OID is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_OID =", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidNotEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_OID <>", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidGreaterThan(String value) {
            addCriterion("MATERIAL_CATALOG_OID >", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_OID >=", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidLessThan(String value) {
            addCriterion("MATERIAL_CATALOG_OID <", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_OID <=", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidLike(String value) {
            addCriterion("MATERIAL_CATALOG_OID like", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidNotLike(String value) {
            addCriterion("MATERIAL_CATALOG_OID not like", value, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidIn(List<String> values) {
            addCriterion("MATERIAL_CATALOG_OID in", values, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidNotIn(List<String> values) {
            addCriterion("MATERIAL_CATALOG_OID not in", values, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidBetween(String value1, String value2) {
            addCriterion("MATERIAL_CATALOG_OID between", value1, value2, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogOidNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_CATALOG_OID not between", value1, value2, "materialCatalogOid");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameIsNull() {
            addCriterion("MATERIAL_CATALOG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameIsNotNull() {
            addCriterion("MATERIAL_CATALOG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_NAME =", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameNotEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_NAME <>", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameGreaterThan(String value) {
            addCriterion("MATERIAL_CATALOG_NAME >", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_NAME >=", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameLessThan(String value) {
            addCriterion("MATERIAL_CATALOG_NAME <", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CATALOG_NAME <=", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameLike(String value) {
            addCriterion("MATERIAL_CATALOG_NAME like", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameNotLike(String value) {
            addCriterion("MATERIAL_CATALOG_NAME not like", value, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameIn(List<String> values) {
            addCriterion("MATERIAL_CATALOG_NAME in", values, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameNotIn(List<String> values) {
            addCriterion("MATERIAL_CATALOG_NAME not in", values, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameBetween(String value1, String value2) {
            addCriterion("MATERIAL_CATALOG_NAME between", value1, value2, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andMaterialCatalogNameNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_CATALOG_NAME not between", value1, value2, "materialCatalogName");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeIsNull() {
            addCriterion("TEMPLATE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeIsNotNull() {
            addCriterion("TEMPLATE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeEqualTo(String value) {
            addCriterion("TEMPLATE_CODE =", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeNotEqualTo(String value) {
            addCriterion("TEMPLATE_CODE <>", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeGreaterThan(String value) {
            addCriterion("TEMPLATE_CODE >", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_CODE >=", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeLessThan(String value) {
            addCriterion("TEMPLATE_CODE <", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeLessThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_CODE <=", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeLike(String value) {
            addCriterion("TEMPLATE_CODE like", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeNotLike(String value) {
            addCriterion("TEMPLATE_CODE not like", value, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeIn(List<String> values) {
            addCriterion("TEMPLATE_CODE in", values, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeNotIn(List<String> values) {
            addCriterion("TEMPLATE_CODE not in", values, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeBetween(String value1, String value2) {
            addCriterion("TEMPLATE_CODE between", value1, value2, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateCodeNotBetween(String value1, String value2) {
            addCriterion("TEMPLATE_CODE not between", value1, value2, "templateCode");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNull() {
            addCriterion("TEMPLATE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNotNull() {
            addCriterion("TEMPLATE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameEqualTo(String value) {
            addCriterion("TEMPLATE_NAME =", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotEqualTo(String value) {
            addCriterion("TEMPLATE_NAME <>", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThan(String value) {
            addCriterion("TEMPLATE_NAME >", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_NAME >=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThan(String value) {
            addCriterion("TEMPLATE_NAME <", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_NAME <=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLike(String value) {
            addCriterion("TEMPLATE_NAME like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotLike(String value) {
            addCriterion("TEMPLATE_NAME not like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIn(List<String> values) {
            addCriterion("TEMPLATE_NAME in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotIn(List<String> values) {
            addCriterion("TEMPLATE_NAME not in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameBetween(String value1, String value2) {
            addCriterion("TEMPLATE_NAME between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotBetween(String value1, String value2) {
            addCriterion("TEMPLATE_NAME not between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidIsNull() {
            addCriterion("BASE_IMG_FILE_OID is null");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidIsNotNull() {
            addCriterion("BASE_IMG_FILE_OID is not null");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidEqualTo(String value) {
            addCriterion("BASE_IMG_FILE_OID =", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidNotEqualTo(String value) {
            addCriterion("BASE_IMG_FILE_OID <>", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidGreaterThan(String value) {
            addCriterion("BASE_IMG_FILE_OID >", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidGreaterThanOrEqualTo(String value) {
            addCriterion("BASE_IMG_FILE_OID >=", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidLessThan(String value) {
            addCriterion("BASE_IMG_FILE_OID <", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidLessThanOrEqualTo(String value) {
            addCriterion("BASE_IMG_FILE_OID <=", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidLike(String value) {
            addCriterion("BASE_IMG_FILE_OID like", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidNotLike(String value) {
            addCriterion("BASE_IMG_FILE_OID not like", value, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidIn(List<String> values) {
            addCriterion("BASE_IMG_FILE_OID in", values, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidNotIn(List<String> values) {
            addCriterion("BASE_IMG_FILE_OID not in", values, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidBetween(String value1, String value2) {
            addCriterion("BASE_IMG_FILE_OID between", value1, value2, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBaseImgFileOidNotBetween(String value1, String value2) {
            addCriterion("BASE_IMG_FILE_OID not between", value1, value2, "baseImgFileOid");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassIsNull() {
            addCriterion("BLOCK_COLOR_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassIsNotNull() {
            addCriterion("BLOCK_COLOR_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassEqualTo(String value) {
            addCriterion("BLOCK_COLOR_CLASS =", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassNotEqualTo(String value) {
            addCriterion("BLOCK_COLOR_CLASS <>", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassGreaterThan(String value) {
            addCriterion("BLOCK_COLOR_CLASS >", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_COLOR_CLASS >=", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassLessThan(String value) {
            addCriterion("BLOCK_COLOR_CLASS <", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_COLOR_CLASS <=", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassLike(String value) {
            addCriterion("BLOCK_COLOR_CLASS like", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassNotLike(String value) {
            addCriterion("BLOCK_COLOR_CLASS not like", value, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassIn(List<String> values) {
            addCriterion("BLOCK_COLOR_CLASS in", values, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassNotIn(List<String> values) {
            addCriterion("BLOCK_COLOR_CLASS not in", values, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassBetween(String value1, String value2) {
            addCriterion("BLOCK_COLOR_CLASS between", value1, value2, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andBlockColorClassNotBetween(String value1, String value2) {
            addCriterion("BLOCK_COLOR_CLASS not between", value1, value2, "blockColorClass");
            return (Criteria) this;
        }

        public Criteria andSizeRateIsNull() {
            addCriterion("SIZE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andSizeRateIsNotNull() {
            addCriterion("SIZE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andSizeRateEqualTo(String value) {
            addCriterion("SIZE_RATE =", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateNotEqualTo(String value) {
            addCriterion("SIZE_RATE <>", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateGreaterThan(String value) {
            addCriterion("SIZE_RATE >", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateGreaterThanOrEqualTo(String value) {
            addCriterion("SIZE_RATE >=", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateLessThan(String value) {
            addCriterion("SIZE_RATE <", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateLessThanOrEqualTo(String value) {
            addCriterion("SIZE_RATE <=", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateLike(String value) {
            addCriterion("SIZE_RATE like", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateNotLike(String value) {
            addCriterion("SIZE_RATE not like", value, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateIn(List<String> values) {
            addCriterion("SIZE_RATE in", values, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateNotIn(List<String> values) {
            addCriterion("SIZE_RATE not in", values, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateBetween(String value1, String value2) {
            addCriterion("SIZE_RATE between", value1, value2, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andSizeRateNotBetween(String value1, String value2) {
            addCriterion("SIZE_RATE not between", value1, value2, "sizeRate");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthIsNull() {
            addCriterion("BASE_IMG_WIDTH is null");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthIsNotNull() {
            addCriterion("BASE_IMG_WIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthEqualTo(Integer value) {
            addCriterion("BASE_IMG_WIDTH =", value, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthNotEqualTo(Integer value) {
            addCriterion("BASE_IMG_WIDTH <>", value, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthGreaterThan(Integer value) {
            addCriterion("BASE_IMG_WIDTH >", value, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_WIDTH >=", value, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthLessThan(Integer value) {
            addCriterion("BASE_IMG_WIDTH <", value, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthLessThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_WIDTH <=", value, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthIn(List<Integer> values) {
            addCriterion("BASE_IMG_WIDTH in", values, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthNotIn(List<Integer> values) {
            addCriterion("BASE_IMG_WIDTH not in", values, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_WIDTH between", value1, value2, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_WIDTH not between", value1, value2, "baseImgWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightIsNull() {
            addCriterion("BASE_IMG_HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightIsNotNull() {
            addCriterion("BASE_IMG_HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightEqualTo(Integer value) {
            addCriterion("BASE_IMG_HEIGHT =", value, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightNotEqualTo(Integer value) {
            addCriterion("BASE_IMG_HEIGHT <>", value, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightGreaterThan(Integer value) {
            addCriterion("BASE_IMG_HEIGHT >", value, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_HEIGHT >=", value, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightLessThan(Integer value) {
            addCriterion("BASE_IMG_HEIGHT <", value, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightLessThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_HEIGHT <=", value, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightIn(List<Integer> values) {
            addCriterion("BASE_IMG_HEIGHT in", values, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightNotIn(List<Integer> values) {
            addCriterion("BASE_IMG_HEIGHT not in", values, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_HEIGHT between", value1, value2, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_HEIGHT not between", value1, value2, "baseImgHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthIsNull() {
            addCriterion("BASE_IMG_STD_WIDTH is null");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthIsNotNull() {
            addCriterion("BASE_IMG_STD_WIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_WIDTH =", value, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthNotEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_WIDTH <>", value, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthGreaterThan(Integer value) {
            addCriterion("BASE_IMG_STD_WIDTH >", value, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_WIDTH >=", value, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthLessThan(Integer value) {
            addCriterion("BASE_IMG_STD_WIDTH <", value, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthLessThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_WIDTH <=", value, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthIn(List<Integer> values) {
            addCriterion("BASE_IMG_STD_WIDTH in", values, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthNotIn(List<Integer> values) {
            addCriterion("BASE_IMG_STD_WIDTH not in", values, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_STD_WIDTH between", value1, value2, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_STD_WIDTH not between", value1, value2, "baseImgStdWidth");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightIsNull() {
            addCriterion("BASE_IMG_STD_HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightIsNotNull() {
            addCriterion("BASE_IMG_STD_HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_HEIGHT =", value, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightNotEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_HEIGHT <>", value, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightGreaterThan(Integer value) {
            addCriterion("BASE_IMG_STD_HEIGHT >", value, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_HEIGHT >=", value, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightLessThan(Integer value) {
            addCriterion("BASE_IMG_STD_HEIGHT <", value, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightLessThanOrEqualTo(Integer value) {
            addCriterion("BASE_IMG_STD_HEIGHT <=", value, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightIn(List<Integer> values) {
            addCriterion("BASE_IMG_STD_HEIGHT in", values, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightNotIn(List<Integer> values) {
            addCriterion("BASE_IMG_STD_HEIGHT not in", values, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_STD_HEIGHT between", value1, value2, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andBaseImgStdHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("BASE_IMG_STD_HEIGHT not between", value1, value2, "baseImgStdHeight");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathIsNull() {
            addCriterion("FEATURE_BLOCK_IMG_PATH is null");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathIsNotNull() {
            addCriterion("FEATURE_BLOCK_IMG_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathEqualTo(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH =", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathNotEqualTo(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH <>", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathGreaterThan(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH >", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathGreaterThanOrEqualTo(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH >=", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathLessThan(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH <", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathLessThanOrEqualTo(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH <=", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathLike(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH like", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathNotLike(String value) {
            addCriterion("FEATURE_BLOCK_IMG_PATH not like", value, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathIn(List<String> values) {
            addCriterion("FEATURE_BLOCK_IMG_PATH in", values, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathNotIn(List<String> values) {
            addCriterion("FEATURE_BLOCK_IMG_PATH not in", values, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathBetween(String value1, String value2) {
            addCriterion("FEATURE_BLOCK_IMG_PATH between", value1, value2, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andFeatureBlockImgPathNotBetween(String value1, String value2) {
            addCriterion("FEATURE_BLOCK_IMG_PATH not between", value1, value2, "featureBlockImgPath");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsIsNull() {
            addCriterion("INNER_RECT_POINTS is null");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsIsNotNull() {
            addCriterion("INNER_RECT_POINTS is not null");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsEqualTo(String value) {
            addCriterion("INNER_RECT_POINTS =", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsNotEqualTo(String value) {
            addCriterion("INNER_RECT_POINTS <>", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsGreaterThan(String value) {
            addCriterion("INNER_RECT_POINTS >", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsGreaterThanOrEqualTo(String value) {
            addCriterion("INNER_RECT_POINTS >=", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsLessThan(String value) {
            addCriterion("INNER_RECT_POINTS <", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsLessThanOrEqualTo(String value) {
            addCriterion("INNER_RECT_POINTS <=", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsLike(String value) {
            addCriterion("INNER_RECT_POINTS like", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsNotLike(String value) {
            addCriterion("INNER_RECT_POINTS not like", value, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsIn(List<String> values) {
            addCriterion("INNER_RECT_POINTS in", values, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsNotIn(List<String> values) {
            addCriterion("INNER_RECT_POINTS not in", values, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsBetween(String value1, String value2) {
            addCriterion("INNER_RECT_POINTS between", value1, value2, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andInnerRectPointsNotBetween(String value1, String value2) {
            addCriterion("INNER_RECT_POINTS not between", value1, value2, "innerRectPoints");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusIsNull() {
            addCriterion("TEMPLATE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusIsNotNull() {
            addCriterion("TEMPLATE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusEqualTo(Integer value) {
            addCriterion("TEMPLATE_STATUS =", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotEqualTo(Integer value) {
            addCriterion("TEMPLATE_STATUS <>", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusGreaterThan(Integer value) {
            addCriterion("TEMPLATE_STATUS >", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("TEMPLATE_STATUS >=", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusLessThan(Integer value) {
            addCriterion("TEMPLATE_STATUS <", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusLessThanOrEqualTo(Integer value) {
            addCriterion("TEMPLATE_STATUS <=", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusIn(List<Integer> values) {
            addCriterion("TEMPLATE_STATUS in", values, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotIn(List<Integer> values) {
            addCriterion("TEMPLATE_STATUS not in", values, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusBetween(Integer value1, Integer value2) {
            addCriterion("TEMPLATE_STATUS between", value1, value2, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("TEMPLATE_STATUS not between", value1, value2, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fa_model_template
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fa_model_template
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}