package com.zfsoft.ha.data.vo;

import lombok.Data;

import java.util.Date;


@Data
public class HaWorkUserSchedule_AppVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.WORK_USER_ID
     *
     * @mbg.generated
     */
    private Long workUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.WORK_DATE
     *
     * @mbg.generated
     */
    private Date workDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.DAY_OF_WEEK
     *
     * @mbg.generated
     */
    private String dayOfWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.YEAR_MONTH
     *
     * @mbg.generated
     */
    private String yearMonth;

    /**
     *午别;1-上午，2-下午，3-全天，4休息
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.AM_OR_PM
     *
     * @mbg.generated
     */
    private String amOrPm;

    /**
     *排班状态;1-可约，2-停约
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.SCHEDULE_STATUS
     *
     * @mbg.generated
     */
    private String scheduleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_user_schedule.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * 显示当天排班的各个时间段的id
     */
    private String t_8_9;
    private String t_9_10;
    private String t_10_11;
    private String t_13_14;
    private String t_14_15;


}