package com.zfsoft.ocr.dbaccess.dao;

import com.zfsoft.ocr.dbaccess.data.DbOcrCallRecord;
import com.zfsoft.ocr.dbaccess.data.DbOcrCallRecordExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DbOcrCallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int countByExample(DbOcrCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int deleteByExample(DbOcrCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int insert(DbOcrCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int insertSelective(DbOcrCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    List<DbOcrCallRecord> selectByExample(DbOcrCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    DbOcrCallRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbOcrCallRecord record, @Param("example") DbOcrCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbOcrCallRecord record, @Param("example") DbOcrCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbOcrCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ocr_call_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbOcrCallRecord record);


    /***
     * @Description: 根据md5查询数据
     * @Author:liangss
     * @Date:2021/12/31
     * @Param: [md5]
     */
    DbOcrCallRecord queryDbOcrCallRecordByMd5(String md5);


    /***
     * @Description: 根据md5和接口查询数据
     * @Author:liangss
     * @Date:2021/12/31
     * @Param: [md5]
     */
    List<DbOcrCallRecord> queryDbOcrCallRecordByMd5AndInterUrl(String md5, String interUrl);
}