package com.zfsoft.ha.dbaccess.data;

import java.util.Date;

public class DbHaWorkService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * 转派id
     */
    private Long turnRecordId;
    /**
     * 转派id
     */
    private String serviceStatus;
    /**
     * 服务人员编号
     */
    private Long workUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.WORK_QUEUE_ID
     *
     * @mbg.generated
     */
    private Long workQueueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.SERVICE_TYPE
     *
     * @mbg.generated
     */
    private String serviceType;

    /**
     * 推送类型
     */
    private String pushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.SERVICE_MEMO
     *
     * @mbg.generated
     */
    private String serviceMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.SX_SERVICE_ID
     *
     * @mbg.generated
     */
    private String sxServiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.QL_CASE_ID
     *
     * @mbg.generated
     */
    private String qlCaseId;

    /**
     * 办件编号（流水号）
     */
    private String caseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.PUSH_MEMO
     *
     * @mbg.generated
     */
    private String pushMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_work_service.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * OPERATOR_NAME 经办人名称
     */
    private String operatorName;


    /**
     * OPERATOR_CARD_NO 经办人身份证
     */
    private String operatorCardNo;


    /**
     * OPERATOR_PHONE 经办人手机号
     */
    private String operatorPhone;

    /**
     * 推送时间
     */
    private Date pushDate;

    public Date getPushDate() {
        return pushDate;
    }

    public void setPushDate(Date pushDate) {
        this.pushDate = pushDate;
    }

    public String getOperatorName() {
        return operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public String getOperatorCardNo() {
        return operatorCardNo;
    }

    public void setOperatorCardNo(String operatorCardNo) {
        this.operatorCardNo = operatorCardNo;
    }

    public String getOperatorPhone() {
        return operatorPhone;
    }

    public void setOperatorPhone(String operatorPhone) {
        this.operatorPhone = operatorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.ID
     *
     * @return the value of t_ha_work_service.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.ID
     *
     * @param id the value for t_ha_work_service.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.WORK_QUEUE_ID
     *
     * @return the value of t_ha_work_service.WORK_QUEUE_ID
     *
     * @mbg.generated
     */
    public Long getWorkQueueId() {
        return workQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.WORK_QUEUE_ID
     *
     * @param workQueueId the value for t_ha_work_service.WORK_QUEUE_ID
     *
     * @mbg.generated
     */
    public void setWorkQueueId(Long workQueueId) {
        this.workQueueId = workQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.SERVICE_TYPE
     *
     * @return the value of t_ha_work_service.SERVICE_TYPE
     *
     * @mbg.generated
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.SERVICE_TYPE
     *
     * @param serviceType the value for t_ha_work_service.SERVICE_TYPE
     *
     * @mbg.generated
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.SERVICE_MEMO
     *
     * @return the value of t_ha_work_service.SERVICE_MEMO
     *
     * @mbg.generated
     */
    public String getServiceMemo() {
        return serviceMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.SERVICE_MEMO
     *
     * @param serviceMemo the value for t_ha_work_service.SERVICE_MEMO
     *
     * @mbg.generated
     */
    public void setServiceMemo(String serviceMemo) {
        this.serviceMemo = serviceMemo == null ? null : serviceMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.SX_SERVICE_ID
     *
     * @return the value of t_ha_work_service.SX_SERVICE_ID
     *
     * @mbg.generated
     */
    public String getSxServiceId() {
        return sxServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.SX_SERVICE_ID
     *
     * @param sxServiceId the value for t_ha_work_service.SX_SERVICE_ID
     *
     * @mbg.generated
     */
    public void setSxServiceId(String sxServiceId) {
        this.sxServiceId = sxServiceId == null ? null : sxServiceId.trim();
    }

    public String getQlCaseId() {
        return qlCaseId;
    }

    public void setQlCaseId(String qlCaseId) {
        this.qlCaseId = qlCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.PUSH_MEMO
     *
     * @return the value of t_ha_work_service.PUSH_MEMO
     *
     * @mbg.generated
     */
    public String getPushMemo() {
        return pushMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.PUSH_MEMO
     *
     * @param pushMemo the value for t_ha_work_service.PUSH_MEMO
     *
     * @mbg.generated
     */
    public void setPushMemo(String pushMemo) {
        this.pushMemo = pushMemo == null ? null : pushMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.CREATE_BY
     *
     * @return the value of t_ha_work_service.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.CREATE_BY
     *
     * @param createBy the value for t_ha_work_service.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.CREATE_DATE
     *
     * @return the value of t_ha_work_service.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.CREATE_DATE
     *
     * @param createDate the value for t_ha_work_service.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.UPDATE_BY
     *
     * @return the value of t_ha_work_service.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.UPDATE_BY
     *
     * @param updateBy the value for t_ha_work_service.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_work_service.UPDATE_DATE
     *
     * @return the value of t_ha_work_service.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_work_service.UPDATE_DATE
     *
     * @param updateDate the value for t_ha_work_service.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public Long getWorkUserId() {
        return workUserId;
    }

    public void setWorkUserId(Long workUserId) {
        this.workUserId = workUserId;
    }

    public Long getTurnRecordId() {
        return turnRecordId;
    }

    public void setTurnRecordId(Long turnRecordId) {
        this.turnRecordId = turnRecordId;
    }

    public String getServiceStatus() {
        return serviceStatus;
    }

    public void setServiceStatus(String serviceStatus) {
        this.serviceStatus = serviceStatus;
    }

    public String getCaseNumber() {
        return caseNumber;
    }

    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber;
    }

    public String getPushType() {
        return pushType;
    }

    public void setPushType(String pushType) {
        this.pushType = pushType;
    }
}