package com.zfsoft.ha.dbaccess.data;

import java.util.Date;


public class DbHaCaseExpress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.QL_CASE_ID
     *
     * @mbg.generated
     */
    private String qlCaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.CASE_EXPRESS_NUM
     *
     * @mbg.generated
     */
    private String caseExpressNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_case_express.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.ID
     *
     * @return the value of t_ha_case_express.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.ID
     *
     * @param id the value for t_ha_case_express.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.QL_CASE_ID
     *
     * @return the value of t_ha_case_express.QL_CASE_ID
     *
     * @mbg.generated
     */
    public String getQlCaseId() {
        return qlCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.QL_CASE_ID
     *
     * @param qlCaseId the value for t_ha_case_express.QL_CASE_ID
     *
     * @mbg.generated
     */
    public void setQlCaseId(String qlCaseId) {
        this.qlCaseId = qlCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.CASE_EXPRESS_NUM
     *
     * @return the value of t_ha_case_express.CASE_EXPRESS_NUM
     *
     * @mbg.generated
     */
    public String getCaseExpressNum() {
        return caseExpressNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.CASE_EXPRESS_NUM
     *
     * @param caseExpressNum the value for t_ha_case_express.CASE_EXPRESS_NUM
     *
     * @mbg.generated
     */
    public void setCaseExpressNum(String caseExpressNum) {
        this.caseExpressNum = caseExpressNum == null ? null : caseExpressNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.CREATE_BY
     *
     * @return the value of t_ha_case_express.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.CREATE_BY
     *
     * @param createBy the value for t_ha_case_express.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.CREATE_DATE
     *
     * @return the value of t_ha_case_express.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.CREATE_DATE
     *
     * @param createDate the value for t_ha_case_express.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.UPDATE_BY
     *
     * @return the value of t_ha_case_express.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.UPDATE_BY
     *
     * @param updateBy the value for t_ha_case_express.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_case_express.UPDATE_DATE
     *
     * @return the value of t_ha_case_express.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_case_express.UPDATE_DATE
     *
     * @param updateDate the value for t_ha_case_express.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}