package com.zfsoft.ha.dbaccess.data;

import java.util.Date;

public class DbHaAkeyReviewRecords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.GROUP_LEADER_ID
     *
     * @mbg.generated
     */
    private Long groupLeaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.GROUP_LEADER_NAME
     *
     * @mbg.generated
     */
    private String groupLeaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.MESSAGE
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.AKEY_REVIEW_DATE
     *
     * @mbg.generated
     */
    private Date akeyReviewDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.DELETE_STATUS
     *
     * @mbg.generated
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ha_akey_review_records.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.ID
     *
     * @return the value of t_ha_akey_review_records.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.ID
     *
     * @param id the value for t_ha_akey_review_records.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.GROUP_LEADER_ID
     *
     * @return the value of t_ha_akey_review_records.GROUP_LEADER_ID
     *
     * @mbg.generated
     */
    public Long getGroupLeaderId() {
        return groupLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.GROUP_LEADER_ID
     *
     * @param groupLeaderId the value for t_ha_akey_review_records.GROUP_LEADER_ID
     *
     * @mbg.generated
     */
    public void setGroupLeaderId(Long groupLeaderId) {
        this.groupLeaderId = groupLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.GROUP_LEADER_NAME
     *
     * @return the value of t_ha_akey_review_records.GROUP_LEADER_NAME
     *
     * @mbg.generated
     */
    public String getGroupLeaderName() {
        return groupLeaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.GROUP_LEADER_NAME
     *
     * @param groupLeaderName the value for t_ha_akey_review_records.GROUP_LEADER_NAME
     *
     * @mbg.generated
     */
    public void setGroupLeaderName(String groupLeaderName) {
        this.groupLeaderName = groupLeaderName == null ? null : groupLeaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.PHONE
     *
     * @return the value of t_ha_akey_review_records.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.PHONE
     *
     * @param phone the value for t_ha_akey_review_records.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.MESSAGE
     *
     * @return the value of t_ha_akey_review_records.MESSAGE
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.MESSAGE
     *
     * @param message the value for t_ha_akey_review_records.MESSAGE
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.AKEY_REVIEW_DATE
     *
     * @return the value of t_ha_akey_review_records.AKEY_REVIEW_DATE
     *
     * @mbg.generated
     */
    public Date getAkeyReviewDate() {
        return akeyReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.AKEY_REVIEW_DATE
     *
     * @param akeyReviewDate the value for t_ha_akey_review_records.AKEY_REVIEW_DATE
     *
     * @mbg.generated
     */
    public void setAkeyReviewDate(Date akeyReviewDate) {
        this.akeyReviewDate = akeyReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.DELETE_STATUS
     *
     * @return the value of t_ha_akey_review_records.DELETE_STATUS
     *
     * @mbg.generated
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.DELETE_STATUS
     *
     * @param deleteStatus the value for t_ha_akey_review_records.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.CREATE_BY
     *
     * @return the value of t_ha_akey_review_records.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.CREATE_BY
     *
     * @param createBy the value for t_ha_akey_review_records.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.CREATE_DATE
     *
     * @return the value of t_ha_akey_review_records.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.CREATE_DATE
     *
     * @param createDate the value for t_ha_akey_review_records.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.UPDATE_BY
     *
     * @return the value of t_ha_akey_review_records.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.UPDATE_BY
     *
     * @param updateBy the value for t_ha_akey_review_records.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ha_akey_review_records.UPDATE_DATE
     *
     * @return the value of t_ha_akey_review_records.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ha_akey_review_records.UPDATE_DATE
     *
     * @param updateDate the value for t_ha_akey_review_records.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}