<!--
 * @Author: haoxinguo haoxinguo@zhuofansoft.com
 * @Date: 2022-08-18 15:16:29
 * @LastEditors: haoxinguo haoxinguo@zhuofansoft.com
 * @LastEditTime: 2022-11-10 16:01:50
 * @FilePath: \zf_web_ui\src\views\pc\operationFlow\components\materialUpload.vue
 * @Description: 材料上传页面
-->
<template>
  <div class="materialUpload-container" v-loading="tableLoading" :element-loading-text="textRemark">
    <div class="materialList">
      <p class="dialogContentTitle" v-if="autoProduceMaterialList.length">
        系统智能生成材料
      </p>
      <div
        class="tableArea"
        v-if="autoProduceMaterialList.length"
        ref="tableArea"
      >
        <el-table
          border
          :data="autoProduceMaterialList"
          ref="autoProduceMaterialListTable"
          style="width: 100%; margin-left: 1px"
        >
          <el-table-column type="index" label="序号" width="50">
          </el-table-column>
          <template v-for="(item, index) in columnList">
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-if="item.prop === 'materialName'"
              align="left"
            >
              <template slot-scope="scope">
                <div class="preview">
                  <span>{{ scope.row.materialName }}</span>
                  <a v-if="scope.row.autoType == 'download'" :href="scope.row.autoUrl">
                    <img :src="require('@/assets/images/home/previewSee.png')" alt="" />
                  </a>
                  <img
                    v-if="
                      scope.row.autoType === 'picture'
                    "
                    @click="preViewFile(scope.row, 'auto')"
                    :src="require('@/assets/images/home/previewSee.png')"
                    alt=""
                  />
                  <a v-if="scope.row.generateType == 'download'" :href="scope.row.generateUrl">
                    <img :src="require('@/assets/images/home/downLoad.png')" alt="" />
                  </a>
                  <img
                    v-if="
                      scope.row.generateType === 'picture'
                    "
                    @click="preViewFile(scope.row, 'generate')"
                    :src="require('@/assets/images/home/downLoad.png')"
                    alt=""
                  />
                  <!-- <img
                    v-show="
                      scope.row.showPreviewType === 'preview' ||
                      scope.row.showPreviewType === 'all'
                    "
                    @click="preView(scope.row, 'autoGenerate')"
                    :src="require('@/assets/images/home/previewSee.png')"
                    alt=""
                  />
                  <img
                    v-show="
                      scope.row.showPreviewType === 'download' ||
                      scope.row.showPreviewType === 'all'
                    "
                    @click="preView(scope.row, 'autoGenerateDown')"
                    :src="require('@/assets/images/home/downLoad.png')"
                    alt=""
                  /> -->
                  <img
                      style="cursor: default"
                      v-show="scope.row.madeMaterialType === 1"
                      :src="require('@/assets/images/home/exemption.png')"
                      alt=""
                  />
                  <!-- <img
                      @click="preView(scope.row, 'empty')"
                      v-if="scope.row.materialEmptyAttoid"
                      :src="require('@/assets/images/home/emptyTable.png')"
                      alt=""
                  /> -->
                  <!-- <img
                      @click="preView(scope.row, 'sample')"
                      v-if="
                      scope.row.materialSampleAddrYl ||
                      scope.row.materialSimpleAddrYl
                    "
                      :src="require('@/assets/images/home/sampleTable.png')"
                      alt=""
                  /> -->
                  <img
                      :src="require('@/assets/images/home/share.png')"
                      @click="toBanshi(scope.row)"
                      alt=""
                  />
                  </div>
              </template>
            </el-table-column>
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-else-if="item.prop === 'operation'"
              align="center"
              width="500"
            >
              <template slot-scope="scope">
                <div class="operationArea">
                  <el-upload
                    class="upload-demo"
                    action
                    :http-request="uploadFiles"
                    :before-upload="beforeUpload"
                    :on-error="uploadError"
                    :file-list="fileList"
                    :show-file-list="showFileList"
                  >
                    <p
                      size="mini"
                      type="primary"
                      @click="
                        pushMaterialOid(scope.row.caseMaterialOid, scope.row)
                      "
                    >
                      本地上传
                    </p>
                  </el-upload>
                  <p @click="scanCodeUpload(scope.row)">扫码上传</p>
                  <p>调取材料</p>
                </div>
              </template>
            </el-table-column>
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-else-if="item.prop === 'mustFlag'"
              align="center"
            >
              <template slot-scope="scope">
                <div class="materialHis">
                  <p class="record">
                    <span
                      :class="scope.row.showUploadPreview ? 'active' : 'noDrop'"
                      @click="openUploadMaterialList(scope.row)"
                    >
                      {{ scope.row.showUploadPreview ? "查阅" : "未上传" }}
                    </span>
                  </p>
                </div>
              </template>
            </el-table-column>
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-else
              :show-overflow-tooltip="true"
            ></el-table-column>
          </template>
        </el-table>
      </div>
      <p class="dialogContentTitle">申请人自备材料</p>
      <div class="tableArea" ref="tableArea">
        <el-table
          border
          :data="selfPreparedMaterials"
          ref="selfPreparedMaterialsTable"
          style="width: 100%; margin-left: 1px"
          :row-key="getRowKey"
          :expand-row-keys="expandRowKeys"
        >
          <el-table-column type="index" label="序号" width="50">
          </el-table-column>
          <template v-for="(item, index) in columnList">
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-if="item.prop === 'materialName'"
              align="left"
            >
              <template slot-scope="scope">
                <div class="preview">
                  <span>{{ scope.row.materialName }}</span>
                  <img
                    style="cursor: default"
                    v-show="scope.row.madeMaterialType === 1"
                    :src="require('@/assets/images/home/exemption.png')"
                    alt=""
                  />
                  <a v-if="scope.row.previewEmptyType == 'download'" :href="scope.row.previewEmptyUrl">
                    <img :src="require('@/assets/images/home/emptyTable.png')" alt="" />
                  </a>
                  <img v-if="scope.row.previewEmptyType == 'picture'" @click="preViewFile(scope.row, 'empty')"
                    :src="require('@/assets/images/home/emptyTable.png')" alt="" />

                  <a v-if="(scope.row.preViewSampleUrl && scope.row.previewSampleType == 'download')"
                    :href="scope.row.preViewSampleUrl">
                    <img v-if="scope.row.preViewSampleUrl" :src="require('@/assets/images/home/sampleTable.png')"
                      alt="" />
                  </a>
                  <img v-if="(scope.row.preViewSampleUrl && scope.row.previewSampleType == 'picture')"
                    @click="preViewFile(scope.row, 'sample')" :src="require('@/assets/images/home/sampleTable.png')"
                    alt="" />
                  <!-- <img
                    @click="preView(scope.row, 'empty')"
                    v-if="scope.row.materialEmptyAddrUrl"
                    :src="require('@/assets/images/home/emptyTable.png')"
                    alt=""
                  />
                  <img
                    @click="preView(scope.row, 'sample')"
                    v-if="
                      scope.row.materialSampleAddrYl ||
                      scope.row.materialSimpleAddrYl
                    "
                    :src="require('@/assets/images/home/sampleTable.png')"
                    alt=""
                  /> -->
                  <!-- <span
                    @click="preView(scope.row, 'sample')"
                    v-if="
                      scope.row.materialSampleAddrYl ||
                      scope.row.materialSimpleAddrYl
                    "
                    >样表</span
                  >
                  <span
                    @click="preView(scope.row, 'empty')"
                    v-if="scope.row.materialEmptyAddr"
                    >空表</span
                  > -->
                    <img
                        :src="require('@/assets/images/home/share.png')"
                        @click="toBanshi(scope.row)"
                        alt=""
                    />
                  </div>
              </template>
            </el-table-column>
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-else-if="item.prop === 'operation'"
              align="center"
              width="500"
            >
              <template slot-scope="scope">
                <div class="operationArea">
                  <el-upload
                    class="upload-demo"
                    multiple
                    :limit="20"
                    :on-exceed="handleExceed"
                    action
                    :http-request="uploadFiles"
                    :before-upload="beforeUpload"
                    :on-error="uploadError"
                    :file-list="fileList"
                    :show-file-list="showFileList"
                  >
                    <p
                      size="mini"
                      type="primary"
                      @click="
                        pushMaterialOid(scope.row.caseMaterialOid, scope.row)
                      "
                    >
                      本地上传
                    </p>
                  </el-upload>
                  <p @click="scanCodeUpload(scope.row)">扫码上传</p>
                  <p>调取材料</p>
                </div>
              </template>
            </el-table-column>
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-else-if="item.prop === 'mustFlag'"
              align="center"
            >
              <template slot-scope="scope">
                <div class="materialHis">
                  <!-- <span v-if="scope.row.flag === 'auto'">自动生成</span>
                  <span v-else-if="scope.row.flag === 'needUpload'"
                    >手动上传</span
                  >
                  <span v-else>可免于提交</span> -->
                  <p class="record">
                    <span
                      :class="scope.row.showUploadPreview ? 'active' : 'noDrop'"
                      @click="openUploadMaterialList(scope.row)"
                    >
                      {{ scope.row.showUploadPreview ? "查阅" : "未上传" }}
                    </span>
                    <!-- <img
                      :src="
                        scope.row.completeSubmit
                          ? require('@/assets/images/home/completeUpload.png')
                          : require('@/assets/images/home/noUpload.png')
                      "
                      alt=""
                    />
                    <img
                      :style="
                        scope.row.showUploadPreview
                          ? { cursor: 'pointer' }
                          : { cursor: 'no-drop' }
                      "
                      @click="openUploadMaterialList(scope.row)"
                      :src="
                        scope.row.showUploadPreview
                          ? require('@/assets/images/home/seePreview.png')
                          : require('@/assets/images/home/disPreview.png')
                      "
                      alt=""
                    /> -->
                  </p>
                </div>
              </template>
            </el-table-column>
            <el-table-column
              :key="index"
              :label="item.label"
              :prop="item.prop"
              v-else
              :show-overflow-tooltip="true"
            ></el-table-column>
          </template>
          <!-- <el-table-column type="expand" width="1">
            <template slot-scope="scope">
              <div class="handle-data-list">
                <div
                  class="handle-data-list-item"
                  v-for="(dataAtta, idx) in scope.row.qlCaseMaterialAttaList"
                  :key="idx"
                >
                  <div class="grid-content qdcg-text">
                    <div class="handle-data-list-item--link">
                      {{
                        dataAtta.originName
                          ? dataAtta.originName
                          : dataAtta.qlSysAtta.originName
                      }}
                    </div>
                  </div>
                  <div class="btnArea">
                    <el-button
                      type="text"
                      icon="el-icon-view"
                      @click="viewFile(dataAtta)"
                      >查看</el-button
                    >
                    <el-button
                      type="text"
                      icon="el-icon-delete"
                      @click.stop="
                        deleteMaterialAtta(idx, scope.row.rowIndex, scope.row)
                      "
                      >删除
                    </el-button>
                  </div>
                </div>
              </div>
            </template>
          </el-table-column> -->
        </el-table>
      </div>
    </div>
    <div class="tips">
      <p>本地上传说明：</p>
      <p>1. 允许上传文件格式：JPG、PNG、PDF；</p>
      <p>2. 最大允许上传文件大小：20M；</p>
      <p>
        3.
        一个材料可上传多份文件，若需要重新上传，请点击状态栏列中“查阅”在弹出框中删除文件后重新上传。
      </p>
    </div>
    <div class="guidance-foot">
      <p @click="toLastStep">上一步</p>
      <p @click="skipData">跳过</p>
      <!-- <p @click="getMaterialList">刷新材料</p> -->
      <p @click="toNextStep">下一步</p>
      <p @click="materialConfirm" v-if="isVideoOpen">材料确认</p>
    </div>
    <el-dialog
      title="材料确认"
      :visible.sync="materialSure"
      width="600px"
      class="assistantNoticeDialog materialSureDialog"
      v-dialogDrag
    >
      <div class="material-list">
        <h2>材料列表：</h2>
        <el-checkbox class="check-all" v-model="checkAll" @change="handleCheckAllChange">全选</el-checkbox>
        <el-checkbox-group v-model="checkList" @change="materialSureType">
          <el-checkbox :key="data.id" v-for="data in materialList" :label="data">{{data.materialName}}</el-checkbox>
        </el-checkbox-group>
      </div>
      <div slot="footer" class="dialog-footer">
        <p @click="materialSure = false">取消</p>
        <p type="primary" @click="materialCollection">下一步</p>
      </div>
    </el-dialog>
    <el-dialog
      v-dialog-drag
      title="扫码上传"
      :visible.sync="eleShow"
      width="600px"
      height="400px"
      class="assistantNoticeDialog uploadMaterial"
      append-to-body
    >
      <div
        style="
          width: 100%;
          display: flex;
          justify-content: center;
          margin-bottom: 20px;
        "
      >
        <img :src="imgUrl" alt="二维码" />
      </div>
      <div style="text-align: center">
        <strong>请用手机扫描上方二维码进行材料上传。</strong>
      </div>
      <div slot="footer" class="dialog-footer">
        <!-- <p @click="uploadCancel">取消</p> -->
        <p @click="uploadSure">已上传</p>
      </div>
    </el-dialog>
    <el-dialog
      v-dialog-drag
      title="预览"
      :visible.sync="showPreview"
      class="assistantNoticeDialog"
      width="80%"
    >
      <div class="previewArea">
        <iframe
          v-if="preType == 'pdf'"
          :src="preViewUrl"
          frameborder="0"
          style="height: 70vh; width: 100%"
        ></iframe>
        <img v-if="preType == 'img'" :src="preViewUrl" alt="img" />
      </div>
    </el-dialog>
    <el-dialog
      :visible.sync="complateVisible"
      width="60rem"
      center
      :show-close="false"
      class="complateVisible"
      v-dialogDrag
    >
      <img :src="require('@/assets/images/pad/complateProgress.png')" alt="" />
      <p>办事人材料是否已经全部提交？</p>
      <div slot="footer" class="dialog-footer">
        <p @click="closeComplateVisible">取消</p>
        <p @click="continueHandle('0')">否，需要办事人补交材料</p>
        <p type="primary" @click="continueHandle('1')">是，材料准备完成</p>
      </div>
    </el-dialog>
    <el-dialog
      title="帮办告知单"
      :visible.sync="showAssistantNotice"
      width="55%"
      class="assistantNoticeDialog"
      v-dialogDrag
    >
      <assistantNotice
        id="print"
        :imgCodeUrl="imgCodeUrl"
        :materialIsAll="materialIsAll"
        :baseUserInfo="baseUserInfo"
        v-if="showAssistantNotice"
      />
      <div slot="footer" class="dialog-footer">
        <p
          @click="toCloseService"
          :class="completePrint && pushUser ? '' : 'noPrint'"
        >
          已打印返回首页
        </p>
        <p @click="pushHandling">一键推送</p>
        <p v-print="printObj">打印</p>
      </div>
    </el-dialog>
    <el-dialog
      title="上传材料列表"
      :visible.sync="showUploadMaterial"
      width="70%"
      class="assistantNoticeDialog"
      v-dialogDrag
    >
      <div class="uploadList">
        <template v-for="(item, index) in showUploadMaterialList">
          <div
            class="uploadItem"
            v-if="item.qlSysAtta || item.materialType === 'upload'"
            :key="index"
            @click="viewFile(item)"
          >
            <img
              @click.stop="deleteMaterialAtta(index, showUploadMaterialIndex)"
              class="delete"
              :src="require('@/assets/images/home/delete.png')"
              alt=""
            />
            <img
              :src="
                require('@/assets/images/home/'+ item.imgView +'Icon.png')
              "
              alt=""
            />
            <p>
              {{
                item.originName ? item.originName : item.qlSysAtta.originName
              }}
            </p>
          </div>
        </template>
      </div>
    </el-dialog>
    <!-- 分享办事人 -->
    <el-dialog :show-close="false" title="分享给办事人员" top="100px　!important" :visible.sync="showHandle" width="800px"
          center class="pageDialog" append-to-body v-dialogDrag>
        <shareHandle @handleClose="handleClose" :list="listData" :tableradioGroup="tableradioGroup"
            :fileData="fileData" />
    </el-dialog>
    <div class="transer-coupon centerXY" v-if="transferShow">
      <img :src="transferUrl" alt="">
    </div>
  </div>
</template>
<script>
import { sendMessage,receiveMessage } from "@/api/modules/helpAgent";
import shareHandle from './shareHandle';
import {
  queryQlCaseMaterialListByCaseOid,
  uploadCaseMaterialFile,
  nextStepSaveQlCase,
  updateQlCaseMaterialList,
  saveOrUpdateCaseMaterialAttaList,
  handlingOnekeyPush,
  pushData,
  querySysAttaByOid,
  queryQlCaseByCaseOid,
} from "@/api/modules/business.js";
import {
    queryWorkQueueList,
} from "@/api/modules/resourceInformation";
import { completeService, updateService } from "@/api/modules/helpAgent";
import { encode, deepClone } from "@/utils/index";
import QRCode from "qrcode";
import assistantNotice from "./assistantNotice.vue";
export default {
  name: "MaterialUpload",
  components: {
    assistantNotice,
    shareHandle
  },
  props: {
    serviceType: {
      type: String,
      default: () => null,
    },
    baseUserInfo: {
      type: Object,
      default: () => {},
    },
    sxServiceMaterialList: {
      type: Array,
      default: () => [],
    },
    currentServiceIndex: {
      type: Number,
      default: () => 0,
    },
  },
  data() {
    let that = this;
    return {
      transferUrl:require('@/assets/images/transfer.gif'),
      transferImg:require('@/assets/images/transfer.gif'),
      transferSuImg:require('@/assets/images/transfer-s.png'),
      transferFaImg:require('@/assets/images/transter-f.png'),
      transferShow:false,
      checkAll:[],
      checkList: [],
      materialSure:false,
      printObj: {
        id: "print", // 这里是要打印元素的ID
        popTitle: "", // 打印的标题
        extraCss: "", // 打印可引入外部的一个 css 文件
        extraHead: "", // 打印头部文字
        previewBeforeOpenCallback() {
          console.log("正在加载预览窗口！");
          console.log(that.msg, this);
        }, // 预览窗口打开之前的callback
        previewOpenCallback() {
          console.log("已经加载完预览窗口，预览打开了！");
        }, // 预览窗口打开时的callback
        openCallback(e) {}, // 调用打印时的callback
        closeCallback(e) {
          that.completePrint = true;
          that.$store.commit("setServiceOperateStatus", true);
        }, // 关闭打印的callback(无法区分确认or取消,暂时无法解决)
        clickMounted() {
          console.log("点击v-print绑定的按钮了！");
        },
      },
      tableLoading: false,
      complateVisible: false,
      showAssistantNotice: false,
      completePrint: false,
      pushUser: false,
      showUploadMaterial: false,
      autoProduceTableHeight: 100,
      tableHeight: 300,
      columnList: [
        { label: "材料名称", prop: "materialName" },
        { label: "是否需要材料上传", prop: "mustFlag" },
        { label: "操作", prop: "operation" },
      ],
      eleShow: false,
      imgUrl: "",
      autoProduceMaterialList: [],
      selfPreparedMaterials: [],
      materialList: this.baseUserInfo.sxServiceMaterialList,
      fileList: [],
      showFileList: false,
      row: {},
      loading: "",
      showPreview: false,
      preType:'', //预览文件类型
      preViewUrl: "",
      materialPreviewList: [],
      associatedAttachmentsList: this.baseUserInfo.associatedAttachmentsList,
      afterService: "",
      getRowKey(row) {
        return row.id; // 返回当前行id
      },
      expandRowKeys: [],
      needSubmittedDataList: [],
      timer: "",
      materialInfo: {},
      isEmpty: false,
      table: null,
      showUploadMaterialList: [],
      showUploadMaterialIndex: 0,
      materialIsAll:0,
      imgCodeUrl:'',
      textRemark:'材料智能制作中请稍候...',
      showHandle: false,
      tableradioGroup: {},
      fileData: '',
      keyValue: 0,
      listData: '',
      isVideoOpen:false,
    };
  },
  computed: {},
  mounted() {
    if(localStorage.getItem('videoNum')){
      this.isVideoOpen = true;
    }
    this.getSituationMaterialListByOids();
  },
  beforeDestroy() {
    clearInterval(this.timer);
  },
  methods: {
    materialConfirm(){
      let sendContent = [];
      let that = this;
      console.log(this.materialList)
      let materialArr = [];
      this.materialList.forEach(function(data){
        
        let qlCaseMaterialAttaList = data.qlCaseMaterialAttaList;
        if(qlCaseMaterialAttaList.length > 0){
          qlCaseMaterialAttaList.forEach(function(item){
            let obj = {};
            if(item.fastdfsNginxUrl){
              obj = {
                name:data.materialName,
                url:item.fastdfsNginxUrl
              };
            }
            if(item.templatePdfUrl){
              obj = {
                name:item.originName,
                url:item.templatePdfUrl
              };
            }
            materialArr.push(obj)
          })
        }
      })
      console.log(materialArr);
      materialArr.forEach(function(file){
        // that.sendFile(file)
        let params = {
          "roomOid":localStorage.getItem('roomId'),
          "accessOid":localStorage.getItem('accessId'),
          "userName":that.$store.state.user.basicUserInfo.name,
          "contentType":"2",
          "fileType":"",
          "sureType":"2",
          "sendContent":JSON.stringify(file),
          "videoNum":localStorage.getItem('videoNum'),
          "receiveMessageOid":"43",
          "informationStatus":""
        }
        sendMessage(params).then(res=>{
        
        })
      })

      // for(let i = 0;i < materialArr.length; i++){
      //   let params = {
      //     "roomOid":localStorage.getItem('roomId'),
      //     "accessOid":localStorage.getItem('accessId'),
      //     "userName":that.$store.state.user.basicUserInfo.name,
      //     "contentType":"2",
      //     "fileType":"",
      //     "sureType":"2",
      //     "sendContent":JSON.stringify(materialArr[i]),
      //     "videoNum":localStorage.getItem('videoNum'),
      //     "receiveMessageOid":"43",
      //     "informationStatus":""
      //   }
      //   setTimeout(() => {
      //     sendMessage(params).then(res=>{
      //     })
      //   }, 2000);
        
        
      // }
      
    },
    sendFile(file){
      let params = {
        "roomOid":localStorage.getItem('roomId'),
        "accessOid":localStorage.getItem('accessId'),
        "userName":this.$store.state.user.basicUserInfo.name,
        "contentType":"2",
        "fileType":"",
        "sureType":"2",
        "sendContent":JSON.stringify(file),
        "videoNum":localStorage.getItem('videoNum'),
        "receiveMessageOid":"43",
        "informationStatus":""
      }
      sendMessage(params).then(res=>{
      
      })
    },
    toBanshi(data) {
        this.fileData = JSON.stringify(data);
        this.tableradioGroup = {};
        let that = this;
        queryWorkQueueList({
            serviceStatus: '2',
            name: '',
            cardNo: '',
            companyName: '',
            queueStatus: '',
        }).then(res => {
            if (res.data.length > 0) {
                that.listData = JSON.stringify(res.data);
                that.showHandle = true;
            } else {
                that.$message.warning("暂无办事人员！");
                that.showHandle = false;
            }
        })
    },
    handleClose() {
        this.showHandle = false;
        this.tableradioGroup = {};
        this.keyValue = Math.random();
    },
    downLoadAutoGenerate(data) {
      // let link = document.createElement("a");
      // let url = data.qlCaseMaterialAttaList[0].templatePdfUrl; //地址
      // // 这里是将url转成blob地址，
      // fetch(url)
      //   .then((res) => res.blob())
      //   .then((blob) => {
      //     // 将链接地址字符内容转变成blob地址

      //     link.href = URL.createObjectURL(blob);
      //     console.log(link.href);
      //     link.download = "";
      //     document.body.appendChild(link);
      //     link.click();
      //   });

      const that = this;
      var oReq = new XMLHttpRequest();
      var URL = data.qlCaseMaterialAttaList[0].templatePdfUrl; // URL 为URL地址
      oReq.open("GET", URL, true);
      oReq.responseType = "blob";
      oReq.onload = function () {
        var file = new Blob([oReq.response], {
          type: "blob",
        });
        FileSaver.saveAs(file); // that.name为文件名
      };
      oReq.send();
    },

    preViewFile(data, type) {
      if (type == 'sample') {
        this.preViewUrl = data.preViewSampleUrl;
      } else if(type == 'empty'){
        this.preViewUrl = data.previewEmptyUrl;
      }else if(type == 'auto'){
        this.preViewUrl = data.autoUrl;
      }else if(type == 'generate'){
        this.preViewUrl = data.generateUrl;
      }
      if (
        /\.(pdf|PDF)$/.test(this.preViewUrl)
      ) {
        this.preType = 'pdf';
      } else if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG)$/.test(this.preViewUrl)) {
        this.preType = 'img';
      }
      this.showPreview = true;
      return;
      let originName = data.materialName;
      console.log("originName"+originName)
      if (type === "sample" || type == 'empty') {
        if (data.materialSampleAddrYl && type == 'sample') {
          this.preViewUrl = data.materialSampleAddrYl;
          // window.open(data.materialSampleAddrYl);
        }
        if (data.materialSimpleAddrYl && type == 'sample') {
          this.preViewUrl = data.materialSimpleAddrYl;
          // window.open(data.materialSimpleAddrYl);
        }

        if (data.materialEmptyAddrUrl && type == 'empty') {
          this.preViewUrl = data.materialEmptyAddrUrl;
          // window.open(data.materialSimpleAddrYl);
        }
        if (
                /\.(pdf|PDF)$/.test(this.preViewUrl)
        ) {
            this.showPreview = true;
            this.preType = 'pdf';
        } else  if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(this.preViewUrl)) {
          this.preType = 'img';
          this.showPreview = true;
        } else {
          const attFix = this.preViewUrl.substring(this.preViewUrl.lastIndexOf(".")+1)
          const url = this.preViewUrl+"?attname="+originName+"."+attFix;
          console.log("url:"+url)
          this.$nextTick(()=>{
            window.open(url);
          })

        }
      } else if (type === "autoGenerate") {
        data.qlCaseMaterialAttaList.forEach((item) => {
          if (item.materialType != "upload" && !item.qlSysAtta) {
            this.preViewUrl = item.templatePdfUrl;
          }
        });
        if (
                /\.(pdf|PDF)$/.test(this.preViewUrl)
        ) {
            this.showPreview = true;
            this.preType = 'pdf';
        } else if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(this.preViewUrl)) {
          this.preType = 'img';
          this.showPreview = true;
        } else {
          const attFix = this.preViewUrl.substring(this.preViewUrl.lastIndexOf(".")+1)
          const url = this.preViewUrl+"?attname="+originName+"."+attFix;
          console.log("url:"+url)
          this.$nextTick(()=>{
            window.open(url);
          })
        }
      } else if (type === "autoGenerateDown") {
        data.qlCaseMaterialAttaList.forEach((item) => {
          if (item.materialType != "upload" && !item.qlSysAtta) {
            this.preViewUrl = item.templatePdfUrlWord;
          }
        });
        if (
                /\.(pdf|PDF)$/.test(this.preViewUrl)
        ) {
            this.showPreview = true;
            this.preType = 'pdf';
        } else if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(this.preViewUrl)) {
          this.preType = 'img';
          this.showPreview = true;
        } else {
          const attFix = this.preViewUrl.substring(this.preViewUrl.lastIndexOf(".")+1)
          const url = this.preViewUrl+"?attname="+originName+"."+attFix;
          console.log("url:"+url)
          this.$nextTick(()=>{
            window.open(url);
          })
        }
      } else {
        this.querySysAttaByOid(data.materialEmptyAttoid,originName);
      }
    },

    querySysAttaByOid(oid,originName) {
      const params = {
        oid: oid,
      };
      querySysAttaByOid(params).then((res) => {
        if (res.code === 200) {
          if (res.data.filePath) {
            this.preViewUrl = res.data.filePath;
            this.originName = res.data.originName;
            if (
                    /\.(pdf|PDF)$/.test(this.preViewUrl)
            ) {
                this.showPreview = true;
                this.preType = 'pdf';
            } else if (
              /\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(this.preViewUrl)
            ) {
              this.preType = 'img';
              this.showPreview = true;
            } else {
              const attFix = this.preViewUrl.substring(this.preViewUrl.lastIndexOf(".")+1)
              const url = this.preViewUrl+"?attname="+originName+"."+attFix;
              console.log("url:"+url)
              window.open(url);

            }
          }
        }
      });
    },

    //打开文件上传列表
    openUploadMaterialList(data) {
      if (!data.showUploadPreview) {
        return;
      }
      this.showUploadMaterial = true;
      this.showUploadMaterialList = data.qlCaseMaterialAttaList;
      console.log(this.showUploadMaterialList);
      let fileObj = {
        doc:true,
        docx:true,
        exel:true,
        gif:true,
        jpeg:true,
        jpg:true,
        pdf:true,
        png:true,
        ppt:true,
      };
      this.showUploadMaterialList.forEach(function(data){
        if(data.originName){
          let typeFile = data.originName.split('.')[1];
          if(typeFile){
            data['imgView'] = typeFile.toLowerCase();
          }else if(data.templatePdfUrl){
            data['imgView'] = 'pdf';
          }
        }else{
          let typeFile = data.qlSysAtta.originName.split('.')[1];
          if(typeFile){
            data['imgView'] = typeFile.toLowerCase();
          }else if(data.templatePdfUrl || data.qlSysAtta.templatePdfUrl ){
            data['imgView'] = 'pdf';
          }
        }
        if(!fileObj[data.imgView]){
          data['imgView'] = 'png';
        }
      })
      this.showUploadMaterialIndex = data.rowIndex;
    },
    handleExceed() {
      this.$message.warning("当前限制上传 最多20 个文件");
    },
    //预览附件
    viewFile(data) {
      if (data.qlSysAtta) {
        this.preViewUrl = data.qlSysAtta.fastdfsNginxUrl;
      } else {
        if (data.fastdfsNginxUrl) {
          this.preViewUrl = data.fastdfsNginxUrl;
        } else {
          this.preViewUrl = data.templatePdfUrl;
        }
      }
      if (
                /\.(pdf|PDF)$/.test(this.preViewUrl)
        ) {
            this.showPreview = true;
            this.preType = 'pdf';
        } else if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(this.preViewUrl)) {
          this.preType = 'img';
          this.showPreview = true;
      } else {
        window.open(this.preViewUrl);
      }
    },
    deleteMaterialAtta(index, rowIndex) {
      this.showUploadMaterialList.splice(index, 1);
      this.materialList[rowIndex].qlCaseMaterialAttaList.splice(index, 1);
      this.$nextTick(() => {
        this.materialList = [...this.materialList];
      });
      if (!this.showUploadMaterialList.length) {
        this.showUploadMaterial = false;
        this.$set(this.materialList[rowIndex], "showUploadPreview", false);
        this.$set(this.materialList[rowIndex], "completeSubmit", false);
      } else {
        if (this.materialList[rowIndex].flag === "auto") {
          const result = this.materialList[
            rowIndex
          ].qlCaseMaterialAttaList.some((item) => {
            return item.qlSysAtta || item.materialType === "upload";
          });
          if (!result) {
            this.showUploadMaterial = false;
            this.$set(this.materialList[rowIndex], "showUploadPreview", false);
          }
          const uploadMaterial = this.materialList[
            rowIndex
          ].qlCaseMaterialAttaList.filter((ite) => {
            return ite.qlSysAtta || ite.materialType === "upload";
          });
          if (
            Number(this.materialList[rowIndex].paperNumber) >
            uploadMaterial.length
          ) {
            this.$set(this.materialList[rowIndex], "completeSubmit", false);
          }
        } else {
          const uploadMaterial =
            this.materialList[rowIndex].qlCaseMaterialAttaList.length;
          if (
            Number(this.materialList[rowIndex].paperNumber) >
            uploadMaterial.length
          ) {
            this.$set(this.materialList[rowIndex], "completeSubmit", false);
          }
        }
      }
    },
    pushHandling() {
      const obj = {
        caseOid: this.baseUserInfo.caseOid,
        serviceOid: this.baseUserInfo.specificMatters.serviceOid,
        pushType: "2",
        name: this.baseUserInfo.name,
        cardNo: this.baseUserInfo.cardNo,
        companyName: this.baseUserInfo.companyName,
        companyCode: this.baseUserInfo.companyCode,
      };
      handlingOnekeyPush(obj).then((res) => {
        if (res.code === 200) {
          this.pushUser = true;
          this.$message.success("推送成功");
        }
      });
    },
    toCloseService() {
      if (this.completePrint && this.pushUser) {
        this.showAssistantNotice = false;
        //跳转到首页
        this.$emit("setResetBaseUserInfo", this.currentServiceIndex);
        this.$emit("nextStep", "mattersHandling");
      }
    },
    // 手机扫码上传 取消
    uploadCancel(){
      this.eleShow = false;
    },
    // 手机扫码上传 确认
    uploadSure(){
      this.textRemark = '材料提交中请稍后...';
      this.eleShow = false;
      this.autoProduceMaterialList = [];
      this.selfPreparedMaterials = [];
      this.getSituationMaterialListByOids();
    },
    //获取材料列表
    getSituationMaterialListByOids() {
      const data = {
        caseOid: this.baseUserInfo.caseOid,
      };
      this.tableLoading = true;
      queryQlCaseMaterialListByCaseOid(data)
        .then((res) => {
          if (res.code === 200) {
            // this.tableHeight = this.$refs.tableArea.clientHeight;
            this.tableLoading = false;
            res.data.autoProduceMaterialList.forEach((item) => {
              item.flag = "auto";
              if (item.qlCaseMaterialAttaList.length) {
                item.qlCaseMaterialAttaList.forEach((ite) => {
                  ite.materialType = "autoGenerate";
                  if (ite.qlSysAtta) {
                    ite.originName = ite.qlSysAtta.originName;
                  } else {
                    ite.originName = item.materialName;
                    if (ite.templatePdfUrl && ite.templatePdfUrlWord) {
                      item.showPreviewType = "all";
                    } else if (ite.templatePdfUrl && !ite.templatePdfUrlWord) {
                      item.showPreviewType = "preview";
                    } else if (!ite.templatePdfUrl && ite.templatePdfUrlWord) {
                      item.showPreviewType = "download";
                    } else {
                      item.showPreviewType = null;
                    }
                  }
                });

                const result = item.qlCaseMaterialAttaList.some((item) => {
                  return item.qlSysAtta;
                });
                if (result) {
                  item.showUploadPreview = true; //是否有上传材料
                } else {
                  item.showUploadPreview = false; //无上传材料
                }
                const uploadMaterial = item.qlCaseMaterialAttaList.filter(
                  (ite) => {
                    return ite.qlSysAtta || ite.materialType === "upload";
                  }
                );
                if (Number(item.paperNumber) > uploadMaterial.length) {
                  item.completeSubmit = false;
                } else {
                  item.completeSubmit = true; //材料附件是否上传完
                }
              } else {
                item.showUploadPreview = false;
                item.completeSubmit = false;
              }
            });
            res.data.needUploadMaterialList.forEach((item) => {
              item.flag = "needUpload";
              if (item.qlCaseMaterialAttaList.length) {
                item.showUploadPreview = true;
                item.qlCaseMaterialAttaList.forEach((ite) => {
                  ite.originName = ite.qlSysAtta.originName;
                });
                const uploadMaterial = item.qlCaseMaterialAttaList.length;
                if (Number(item.paperNumber) > uploadMaterial.length) {
                  item.completeSubmit = false;
                } else {
                  item.completeSubmit = true;
                }
              } else {
                item.showUploadPreview = false;
                item.completeSubmit = false;
              }
            });
            res.data.noSubmissionMaterialList.forEach((item) => {
              item.flag = "noSubmission";
              item.madeMaterialType = 1; //免提交
              if (item.qlCaseMaterialAttaList.length) {
                item.showUploadPreview = true;
                item.qlCaseMaterialAttaList.forEach((ite) => {
                  ite.originName = ite.qlSysAtta.originName;
                });
                const uploadMaterial = item.qlCaseMaterialAttaList.length;
                if (Number(item.paperNumber) > uploadMaterial.length) {
                  item.completeSubmit = false;
                } else {
                  item.completeSubmit = true;
                }
              } else {
                item.showUploadPreview = false;
                item.completeSubmit = false;
              }
            });
            this.materialList = [
              ...res.data.autoProduceMaterialList,
              ...res.data.needUploadMaterialList,
              ...res.data.noSubmissionMaterialList,
            ];
            this.materialList.forEach((item, index) => {
              item.rowIndex = index;
              item.quantityMaterials = 0;
              if (item.qlCaseMaterialAttaList.length) {
                if (item.flag === "auto") {
                  item.quantityMaterials = item.qlCaseMaterialAttaList.length;
                  this.expandRowKeys.push(item.id);
                }

                // if(item.){}
              } else {
                item.showUploadPreview = false;
              }
              if (item.flag === "auto") {
                this.autoProduceMaterialList.push(item);
              } else {
                this.selfPreparedMaterials.push(item);
              }

              let targetData = item;
              //样表
              if (targetData.materialSampleAddrYl || targetData.materialSimpleAddrYl) {
                if (targetData.materialSampleAddrYl) {
                  targetData['preViewSampleUrl'] = targetData.materialSampleAddrYl;
                }
                if (targetData.materialSimpleAddrYl) {
                  targetData['preViewSampleUrl'] = targetData.materialSimpleAddrYl;
                }
                if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(targetData.preViewSampleUrl)) {
                  targetData['previewSampleType'] = 'picture';
                } else {
                  targetData['previewSampleType'] = 'download';
                  const attFix = targetData.preViewSampleUrl.substring(targetData.preViewSampleUrl.lastIndexOf(".") + 1)
                  const url = targetData.preViewSampleUrl + "?attname=" + targetData.simpleOriginName;
                  targetData.preViewSampleUrl = url;
                }
              }
              //空表
              if (targetData.materialEmptyAddrUrl) {
                targetData['previewEmptyUrl'] = targetData.materialEmptyAddrUrl;
                if (
                  /\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(targetData.materialEmptyAddrUrl)
                ) {
                  targetData['previewEmptyType'] = 'picture';
                } else {
                  targetData['previewEmptyType'] = 'download';
                  const attFix = targetData['previewEmptyUrl'].substring(targetData['previewEmptyUrl'].lastIndexOf(".") + 1)
                  const url = targetData['previewEmptyUrl'] + "?attname=" + targetData.emptyOriginName;
                  targetData['previewEmptyUrl'] = url;
                }
              } else {
                targetData['previewEmptyType'] = '';
                targetData['previewEmptyUrl'] = '';
              }
              // 智能生成
              if (targetData.showPreviewType === 'preview' || targetData.showPreviewType === 'all') {
                targetData.qlCaseMaterialAttaList.forEach((list) => {
                  if (list.materialType != "upload" && !list.qlSysAtta) {
                    targetData['autoUrl'] = list.templatePdfUrl;
                  }
                });
                if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(targetData['autoUrl'])) {
                  targetData['autoType'] = 'picture';
                } else {
                  targetData['autoType'] = 'download';
                  const attFix = targetData['autoUrl'].substring(targetData['autoUrl'].lastIndexOf(".")+1)
                  const url = targetData['autoUrl']+"?attname="+ targetData.materialName.split(".")[0] +"."+attFix;
                  targetData['autoUrl'] = url;
                }
              }
              // autoGenerateDown
              if (targetData.showPreviewType === 'download' || targetData.showPreviewType === 'all') {
                targetData.qlCaseMaterialAttaList.forEach((list) => {
                  if (list.materialType != "upload" && !list.qlSysAtta) {
                    targetData['generateUrl'] = list.templatePdfUrlWord;
                  }
                });
                if (/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(targetData['generateUrl'])) {
                  targetData['generateType'] = 'picture';
                } else {
                  targetData['generateType'] = 'download';
                  const attFix = targetData['generateUrl'].substring(targetData['generateUrl'].lastIndexOf(".")+1)
                  const url = targetData['generateUrl']+"?attname="+ targetData.materialName.split(".")[0] +"."+attFix;
                  console.log("url:"+url)
                  targetData['generateUrl'] =url;
                }
              }


            });
            this.$nextTick(() => {
              this.materialList = [...this.materialList];
            });

            this.$emit("setSxServiceMaterialList", this.materialList);
          }
        })
        .catch((err) => {
          this.tableLoading = false;
        });
    },
    /** 上传附件 */
    uploadFiles(file) {
      const loading = this.$loading({
        lock: true,
        text: "正在上传文件",
        spinner: "el-icon-loading",
        background: "rgba(0, 0, 0, 0.7)",
      });
      let formData = new FormData();
      formData.append("files", file.file);
      uploadCaseMaterialFile(formData)
        .then((res) => {
          loading.close();
          if (res.code === 200) {
            if (res.data.length) {
              res.data.forEach((ite) => {
                ite.materialType = "upload";
              });

              this.materialList[this.attaIndex].qlCaseMaterialAttaList = [
                ...this.materialList[this.attaIndex].qlCaseMaterialAttaList,
                ...res.data,
              ];
              this.materialList[this.attaIndex].collectionType = "2";
              this.materialList[this.attaIndex].showUploadPreview = true;

              const uploadMaterial = this.materialList[
                this.attaIndex
              ].qlCaseMaterialAttaList.filter((ite) => {
                return ite.materialType === "upload";
              });
              if (
                Number(this.materialList[this.attaIndex].paperNumber) >
                uploadMaterial.length
              ) {
                this.$set(
                  this.materialList[this.attaIndex],
                  "completeSubmit",
                  false
                );
              } else {
                this.$set(
                  this.materialList[this.attaIndex],
                  "completeSubmit",
                  true
                );
              }

              this.$emit("setSxServiceMaterialList", this.materialList);
              this.$nextTick(() => {
                this.materialList = [...this.materialList];
              });
              // this.toUpdateQlCaseMaterialList(
              //   this.materialList[this.attaIndex]
              // );
              // this.submitFileForm();
            } else {
              this.$message.error("材料溜走了");
            }
          }
        })
        .catch((err) => {
          this.uploadError();
        });
    },
    //扫码上传
    async scanCodeUpload(data) {
      clearInterval(this.timer);
      this.materialInfo = {
        caseMaterialOid: data.caseMaterialOid,
        materialOid: data.materialOid,
      };
      this.imgUrl = await QRCode.toDataURL(
          //数据
          // `https://onlineserve.shhuangpu.gov.cn/materialUpload/materialUpload?caseMaterialOid=${data.caseMaterialOid}&materialOid=${data.materialOid}&collectionType=2`
          // `http://101.230.251.254:81/materialUpload?caseMaterialOid=${data.caseMaterialOid}&materialOid=${data.materialOid}&collectionType=2`
         //`http://172.168.253.71:81/materialUpload?caseMaterialOid=${data.caseMaterialOid}&materialOid=${data.materialOid}&collectionType=2`
        `https://onlineserve.shhuangpu.gov.cn/bangban/materialUpload?caseMaterialOid=${data.caseMaterialOid}&materialOid=${data.materialOid}&collectionType=2`

         );
      this.eleShow = true;
      // this.getMaterialList();
    },
    //上传之前
    beforeUpload(file) {
      if (
        file.name.indexOf("%00") > -1 ||
        file.name.indexOf("./") > -1 ||
        file.name.indexOf(".\\") > -1
      ) {
        this.msgError("上传文件名称非法！");
        return false;
      }
      if (!/\.(gif|jpg|jpeg|png|GIF|JPG|PNG|pdf|PDF)$/.test(file.name)) {
        this.$message.warning("只允许上传图片和pdf文件");
        return false;
      }
      const fileSize = file.size;
      if (0 == fileSize) {
        this.msgError("上传文件不能为空！");
        return false;
      }
      const isLt2M = file.size / 1024 / 1024 < 30;
      if (!isLt2M) {
        this.msgError("上传文件大小不能超过 30MB！");
      }
      return isLt2M;
    },
    //失败后返回
    uploadError(resp) {
      // this.$message.error("文件上传失败");
    },

    //更新材料关联
    toUpdateQlCaseMaterialList() {
      const params = [];
      this.materialList.forEach((item) => {
        if (item.qlCaseMaterialAttaList.length - item.quantityMaterials > 0) {
          item.collectionFlag = 1;
          item.attaList = item.qlCaseMaterialAttaList;
          item.collectionNumber =
            item.qlCaseMaterialAttaList.length - item.quantityMaterials;
          params.push(item);
        }else if(item.collectionStatus){
          item.collectionFlag = 1;
          params.push(item);
        }
      });
      updateQlCaseMaterialList(params).then((res) => {
        if (res.code === 200) {
          console.log(res.data);
        }
      });
    },

    // 提交上传文件
    submitFileForm() {
      const params = [];
      this.materialList.forEach((item) => {
        let obj = {};
        if(item.collectionStatus){
          obj = {
            caseMaterialOid: item.caseMaterialOid,
            collectionType:item.collectionType,
            materialOid: item.materialOid,
            collectionFlag: 1,
            qlCaseMaterialAttaList: [],
          };
        }
        if (item.qlCaseMaterialAttaList.length - item.quantityMaterials > 0) {
          obj = {
            caseMaterialOid: item.caseMaterialOid,
            collectionType: "2",
            materialOid: item.materialOid,
            collectionFlag: 1,
            qlCaseMaterialAttaList: [],
          };
          if (item.qlCaseMaterialAttaList.length) {
            item.qlCaseMaterialAttaList.forEach((it) => {
              const ob = {
                attaOid: it.attaOid,
                caseMaterialOid: item.caseMaterialOid,
                src: it.fastdfsNginxUrl,
              };
              obj.qlCaseMaterialAttaList.push(ob);
            });
          }
        }
        if(obj['caseMaterialOid']) {
          params.push(obj);
        }

      });
      saveOrUpdateCaseMaterialAttaList(params)
        .then((res) => {
          if (res.code === 200) {
            // this.$message.success("材料附件已更新");
            // this.showAssistantNotice = true;
          }
        })
        .catch((err) => {
          console.log(err);
        });
    },

    //扫码上传接口轮询
    getMaterialList() {
      const that = this;
      that.isEmpty = false;
      // that.timer = setInterval(() => {
        const data = {
          caseOid: that.baseUserInfo.caseOid,
        };
        queryQlCaseMaterialListByCaseOid(data).then((res) => {
          if (res.code === 200) {
            // let materialList = [];
            let materialList = [
              ...res.data.autoProduceMaterialList,
              ...res.data.needUploadMaterialList,
              ...res.data.noSubmissionMaterialList,
            ];
            materialList.forEach((item, index) => {
              if (
                item.caseMaterialOid === this.materialInfo.caseMaterialOid &&
                item.materialOid === this.materialInfo.materialOid
              ) {
                if (item.qlCaseMaterialAttaList.length) {
                  if (!this.materialList[index].qlCaseMaterialAttaList.length) {
                    that.isEmpty = true;
                    this.materialList[index].qlCaseMaterialAttaList =
                      item.qlCaseMaterialAttaList;
                  } else {
                    item.qlCaseMaterialAttaList.forEach((ite) => {
                      const result = this.materialList[
                        index
                      ].qlCaseMaterialAttaList.find((data) => {
                        return data.attaOid === ite.attaOid;
                      });
                      if (!result) {
                        this.materialList[index].qlCaseMaterialAttaList.push(
                          ite
                        );
                      }
                    });
                  }
                  this.$nextTick(() => {
                    this.materialList = [...this.materialList];
                    this.autoProduceMaterialList = [
                      ...this.autoProduceMaterialList,
                    ];
                    this.selfPreparedMaterials = [
                      ...this.selfPreparedMaterials,
                    ];
                  });
                }
              }
            });
          }
        });
      // }, 50000000);
    },

    pushMaterialOid(materialOid, row) {
      this.materialOid = materialOid;
      this.attaIndex = row.rowIndex; //标识材料索引
      this.row = row;
    },
    toLastStep() {
      if (this.baseUserInfo.skipSmartForms) {
        this.$emit("nextStep", "essentialInformation", "2");
      } else {
        this.$emit("nextStep", "intelligentFormFilling", 3);
      }
    },
    // 跳过
    skipData() {
      this.materialSure = true;
      this.checkList = [];
      this.materialList.forEach(function(list){
        list['collectionStatus'] = false;
      })
    },
    // 全选 变化
    handleCheckAllChange(val){
      if(val){
        this.checkList = this.materialList;
      }else{
        this.checkList = [];
      }
    },
    // 跳过 材料选择
    materialSureType(){
      if(this.checkList.length == this.materialList.length){
        this.checkAll = true;
      }else{
        this.checkAll = false;
      }
    },
    //跳过  下一步
    materialCollection(){
      let that = this;
      that.materialList.forEach(function(list){
        that.checkList.forEach(function(check){
          if(list.materialOid == check.materialOid){
            list.collectionType = '1';
            list['collectionStatus'] = true; //设置跳过，不作判断
          }
        })
      })
      this.materialSure = false;
      this.complateVisible = true;
    },
    toNextStep() {
      this.complateVisible = true;
    },

    nextStepSaveQlCase(status) {
      let that =this;
      nextStepSaveQlCase({
        ...this.baseUserInfo.fillUserInfo,
        id: "",
        applyOid: "",
        applyNumber: "1",
        extOid: "",
        caseOid: this.baseUserInfo.caseOid,
        caseStatus: status,
        applyUserType: this.baseUserInfo.fillUserInfo.applyUserType,
        serviceOid: this.baseUserInfo.specificMatters.serviceOid,
        sourceType: "1",
        caseNumber: this.baseUserInfo.caseNumber,
        sxServiceMaterialList: this.baseUserInfo.sxServiceMaterialList,
        qlCaseTitleValList: this.baseUserInfo.qlCaseTitleValList,
      }).then((res) => {
        if (res.code === 200) {
            if (status === "1") {
              that.pushData(function(num){
                if(num == '1'){
                  that.transferUrl = that.transferSuImg;
                  that.$message.success("推送成功");
                }else{
                  that.transferUrl = that.transferFaImg;
                }
                setTimeout(function(){
                  that.transferShow = false;
                  that.$store.commit("setServiceOperateStatus", true);
                  // this.completeService(status);
                  that.toUpdateService(status);
                  that.showAssistantNotice = true;
                },1500)
              });
            }else{
              that.showAssistantNotice = true;
            }


        }
      });
    },
    // 推送办件
    pushData(callBack) {
      this.transferUrl = this.transferImg;
      this.transferShow = true;
      const params = {
        caseOid: this.baseUserInfo.caseOid,
      };
      pushData(params).then((res) => {
        if (res.code == 200) {
          callBack('1')
        }else{
          callBack('0')
        }
      }).catch((err) => {
        console.log(err);
        callBack('0')
      });
    },
    //完成服务
    completeService(status) {
      // console.log("serviceStatus------------"+status)
      let data = {
        workQueueId: this.baseUserInfo.id,
        serviceType: this.baseUserInfo.serviceType,
        serviceMemo: this.baseUserInfo.specificMatters.serviceName
          ? encode(this.baseUserInfo.specificMatters.serviceName)
          : "",
        sxServiceId: this.baseUserInfo.specificMatters.serviceOid,
        qlCaseId: this.baseUserInfo.caseOid,
        pushMemo: "",
        nextServiceAdvise: "3",
        distributionAdvise: "",
        serviceStatus: status === "1" ? "1" : "2",
        caseNumber: this.baseUserInfo.caseNumber,
      };
      completeService(data)
        .then((res) => {
          this.complateVisible = false;
          if (res.code === 200) {
            this.$store.commit("setServiceOperateStatus", true);
            this.toUpdateService(status);
          }
        })
        .catch((err) => {
          this.complateVisible = false;
        });
    },

    //更新服务
    toUpdateService(status) {
      // console.log("serviceStatus------------------"+status)
      const params = {
        haWorkServiceId: this.baseUserInfo.haWorkServiceId,
        serviceStatus: status === "1" ? "1" : "2",
      };
      updateService(params).then((res) => {
        if (res.code === 200) {
        }
      });
    },

    closeComplateVisible() {
      this.complateVisible = false;
    },
    continueHandle(type) {
      clearInterval(this.timer);
      if (type === "1") {
        const result = this.materialList.some((item) => {
          const uploadMaterial = item.qlCaseMaterialAttaList.filter((ite) => {
            return ite.qlSysAtta || ite.materialType === "upload";
          });
          if(!item.collectionStatus){
            return Number(item.paperNumber) > uploadMaterial.length;
          }else{
            return false;  //纸质收取 不判断
          }

        });
        if (result) {
          this.$message.warning("材料未全部提交");
          return;
        }
      }
      this.getQueryQlCaseByCaseOid();
      this.materialIsAll = type;
      this.toUpdateQlCaseMaterialList();
      this.submitFileForm();
      this.nextStepSaveQlCase(type);
    },
    //查询办件信息
    getQueryQlCaseByCaseOid() {
      queryQlCaseByCaseOid({ caseOid: this.baseUserInfo.caseOid }).then(
        (res) => {
          if (res.code === 200) {
            this.imgCodeUrl = res.data.applay.credentialType + ';' + res.data.applay.credentialNumber;
          }
        }
      );
    },
  },
  watch: {
    sxServiceMaterialList: {
      handler(val) {
        if (val) {
          this.materialList = val;
        }
      },
      deep: true,
    },
  },
};
</script>
<style lang="scss" scoped>
  .transer-coupon{
    position: fixed;
    top:0;
    right: 0;
    left: 0;
    bottom: 0;
    background: rgba(0,0,0,0.5);
    z-index: 9999;
    img{
      width: 300px;
    }
  }
  .material-list{
    text-align: left;
    .el-checkbox{
      display: block;
      margin: 10px 0;
    }
  }
.materialUpload-container {
  width: 100%;
  height: 100%;
  background-color: #fff;
  padding: 1.5rem 1.5rem;
  // overflow: hidden;
  overflow-y: auto;

  .materialList {
    width: 100%;
    height: auto;
    overflow-x: hidden;
    overflow-y: auto;
    .dialogContentTitle {
      width: 15.8333rem;
      height: 2.5rem;
      display: flex;
      align-items: center;
      justify-content: flex-start;
      padding-left: 3.25rem;
      position: relative;
      margin: 1.25rem 0;
      &:nth-child(1) {
        background: url("@/assets/images/home/interMaterialBack.png") no-repeat;
        background-size: 100% 100%;
        font-size: 1.3333rem;
        font-family: Microsoft YaHei;
        font-weight: 400;
        color: #0f3255;
      }
      &:nth-child(3) {
        background: url("@/assets/images/home/selfMaterialBack.png") no-repeat;
        background-size: 100% 100%;
        font-size: 1.3333rem;
        font-family: Microsoft YaHei;
        font-weight: 400;
        color: #482a07;
      }
    }
    .tableArea {
      width: 100%;
      height: auto;
      .el-table {
        width: 100%;
        ::v-deep .el-table__body-wrapper {
          &::-webkit-scrollbar {
            width: 0.4375rem;
            background-color: #fff;
          }

          &::-webkit-scrollbar-thumb {
            width: 0.4375rem;
            height: 0.625rem !important;
            // background: linear-gradient(270deg, #bf9e63 0%, #dfca98 100%);
            background: linear-gradient(270deg, #2473ff 0%, #56b1fd 100%);
            border-radius: 4px;
          }

          .el-table__body {
            .el-table__row {
              .el-table__cell {
                .cell {
                  .preview {
                    width: 100%;
                    height: 100%;
                    display: flex;
                    align-items: center;
                    justify-content: flex-start;
                    span {
                      font-size: 14px;
                      margin-right: 17px;
                      font-family: Microsoft YaHei;
                      font-weight: 400;
                      color: #2a344c;
                    }
                    a {
                      display: inline-flex;
                    }
                    img {
                      width: 17px;
                      cursor: pointer;
                      margin-right: 19px;
                      cursor: pointer;
                    }
                    .share{
                      border-radius: 4px;
                      display: inline-block;
                      min-width: 40px;
                      background: linear-gradient(265deg, #23a4ff 0%, #2778ff 100%);
                      color: #fff;
                      height: 25px;
                      text-align: center;
                      font-size: 14px;
                      cursor: pointer;
                      &:hover{
                        opacity: 0.8;
                      }
                    }
                  }
                  .materialHis {
                    width: 100%;
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                    .record {
                      width: 100%;
                      height: 100%;
                      padding-right: 3rem;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      span {
                        font-size: 14px;
                        font-family: Microsoft YaHei;
                        font-weight: 400;
                      }
                      .active {
                        text-decoration: underline;
                        color: #2575ff;
                        cursor: pointer;
                      }
                      .noDrop {
                        color: #2a344c;
                        cursor: no-drop;
                      }
                    }
                  }
                }
              }
            }
          }
        }

        .el-table__expanded-cell {
          width: 100%;
          height: auto;

          .handle-data-list {
            width: 100%;
            height: auto;

            .handle-data-list-item {
              width: 100%;
              height: 3.125rem;
              padding: 0 2.5rem;
              display: flex;
              align-items: center;
              justify-content: space-between;
              .btnArea {
                width: 12rem;
              }
            }
          }
        }

        ::v-deep .el-table__expand-icon {
          visibility: hidden;
        }

        .operationArea {
          width: 100%;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;

          p {
            cursor: pointer;
            padding: 0.5rem 1rem;
            margin-right: 1.5rem;
            display: flex;
            align-items: center;
            justify-content: center;

            font-family: MicrosoftYaHei;
            font-size: 1.5rem;
            font-weight: normal;
            font-stretch: normal;
            letter-spacing: 0px;
            color: #ffffff;
            border-radius: 3px;

            &:nth-child(1) {
              background: linear-gradient(265deg, #23a4ff 0%, #2778ff 100%);
            }

            &:nth-child(2) {
              background: linear-gradient(265deg, #23a4ff 0%, #2778ff 100%);
              margin-right: 1.0714rem;
            }

            &:nth-child(3) {
              background: linear-gradient(125deg, #f69b4a 0%, #fe8034 100%);
            }
          }
        }
      }
    }
  }
  .tips {
    width: 100%;
    height: auto;
    background: rgba(98, 154, 240, 0.05);
    border: 1px dotted #629af0;
    padding: 20px;
    margin-top: 21px;
    p {
      padding: 0;
      margin: 0;
      font-size: 14px;
      font-family: Microsoft YaHei;
      font-weight: 400;
      color: #2a344c;
      text-align: left;
      line-height: 30px;
      &:nth-child(1) {
        font-family: Microsoft YaHei;
        font-weight: 400;
        color: #121b2f;
      }
    }
  }
  .guidance-foot {
    margin-top: 6.6667rem;
    width: 100%;
    height: 6.375rem;
    display: flex;
    align-items: center;
    justify-content: center;

    p {
      cursor: pointer;
      padding: 0 3.75rem;
      width: auto;
      height: 5.1667rem;
      background: #ffffff;
      border: 1px solid #4988f2;
      box-shadow: 0px 0px 1.5rem 0px rgba(40, 107, 198, 0.31);
      border-radius: 2.5833rem;
      font-size: 1.8333rem;
      font-family: Microsoft YaHei;
      font-weight: 400;
      color: #2473ff;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-right: 2.1875rem;

      &:nth-child(3) {
        color: #ffffff;
        background: linear-gradient(90deg, #2473ff 0%, #56b1fd 100%);
        box-shadow: 0px 0px 1.5rem 0px rgba(40, 107, 198, 0.31);
      }
    }
  }
}

.el-dialog__wrapper {
  .el-dialog {
    .el-dialog__body {
      .previewArea {
        width: 100%;

        img {
          width: 100%;
        }
      }

      .materialPreviewArea {
        width: 100%;
        height: 75vh;
      }
      .uploadList {
        width: 100%;
        height: auto;
        padding: 2.5rem;
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        flex-wrap: wrap;
        .uploadItem {
          width: 11.7647rem;
          height: 17.6471rem;
          margin-right: 2.5rem;
          position: relative;
          cursor: pointer;
          .delete {
            width: 3rem;
            height: 3rem;
            position: absolute;
            top: -1.5rem;
            left: 0.5rem;
            z-index: 1000;
          }
          img {
            width: 11.7647rem;
            height: 11.7647rem;
            cursor: pointer;
          }
          p {
            width: 100%;
            margin-top: 1.5rem;
            font-size: 1.7647rem;
            font-family: Microsoft YaHei;
            font-weight: 400;
            color: #373737;
            overflow: hidden; // 溢出隐藏
            display: -webkit-box; //  自适应布局 弹性伸缩盒子
            -webkit-box-orient: vertical; //垂直排列子元素 伸缩盒子的子元素排列
            -webkit-line-clamp: 2; //最多显示几行 多出部分。。。显示
            text-overflow: ellipsis; // 显示省略号
          }
        }
      }
    }
  }
}

.complateVisible {
  ::v-deep .el-dialog {
    width: 40rem;
    // height: 25.125rem;
    margin-top: calc(50vh - 12.5625rem) !important;

    .el-dialog__header {
      background: #fff !important;
    }

    .el-dialog__body {
      width: 100%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 0 !important;

      img {
        width: 9rem;
      }

      p {
        font-size: 2rem;
        font-family: Source Han Sans CN;
        font-weight: 500;
        color: #373737;
        margin: 0.9375rem;
        padding: 0;
      }
    }

    .el-dialog__footer {
      height: 4.6875rem;
      margin-top: 5.9375rem;

      .dialog-footer {
        width: 100%;
        height: 100%;
        display: flex;
        align-items: center;
        p {
          height: 100%;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 1.8rem;
          font-family: Source Han Sans CN;
          font-weight: 500;
          padding: 0;
          margin: 0;
          &:nth-child(1) {
            width: 33%;
            background: #a0bce1;
            border-radius: 0px 0px 0px 0.625rem;
            color: #645c4b;
          }

          &:nth-child(2) {
            width: 34%;
            background: #6090e3;
            color: #dbd2d2;
            border-radius: 0;
          }

          &:nth-child(3) {
            width: 34%;
            background: #3675e2;
            color: #ffffff;
            border-radius: 0px 0px 0.625rem 0;
          }
        }
      }
    }
  }
}
.assistantNoticeDialog {
  ::v-deep .el-dialog {
    height: 80vh;
    .dialog-footer {
      p {
        &:nth-child(1) {
          background: #ffffff;
          border: 1px solid #4988f2;
          box-shadow: 0px 0px 1.8125rem 0px rgba(204, 177, 121, 0.31);
          color: #2473ff;
          margin-right: 2.1875rem;
          cursor: pointer;
        }

        &:nth-child(2) {
          background: linear-gradient(90deg, #0093e7 0%, #17c3f5 100%);
          box-shadow: 0px 0px 1.5rem 0px rgb(40 107 198 / 31%);
          color: #ffffff;
          border: none;
        }

        &:nth-child(3) {
          color: #ffffff;
          background: linear-gradient(90deg, #2473ff 0%, #56b1fd 100%);
        }
      }
      .noPrint {
        cursor: not-allowed !important;
        border-color: #dcdfe6 !important;
        color: #c0c4cc !important;
      }
    }
  }
}
.procedure {
  word-wrap: break-word;
}
.uploadMaterial{
  ::v-deep .el-dialog{
    height: 420px;
  }
}
@media print {
  .noPrint {
    display: none;
  }
}
.materialSureDialog{
  .material-list{
    height: 350px;
    overflow-y: auto;
  }
  .el-dialog .dialog-footer p:nth-child(1),.el-dialog .dialog-footer p:nth-child(2){
    padding: 1.3125rem 40px 1.4375rem 40px;
    border-radius: 25px;
  }
}
.check-all{
  margin-bottom: 10px;
}
iframe body img{
  width: 100%;
}
</style>
