package com.zfsoft.microservice.platform.data.vo;

import lombok.Data;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * @description:  区划信息实体类
 * @author: wuxx
 * @Date: 2020/8/28 13:04
 **/
@Data
@ToString
public class SysDistrictHpVo {
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.DISTRICT_OID
     *
     * @mbggenerated
     */
    private String districtOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.PARENT_OID
     *
     * @mbggenerated
     */
    private String parentOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.LEVEL_DICT_OID
     *
     * @mbggenerated
     */
    private String levelDictOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.IS_ABLE
     *
     * @mbggenerated
     */
    private Integer isAble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.DIS_NAME_STR
     *
     * @mbggenerated
     */
    private String disNameStr;

    /**
     * 关联父类
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_district.IMAGE_ATTA_OID
     *
     * @mbggenerated
     */
    private String imageAttaOid;


}
