package com.zfsoft.microservice.platform.dbaccess.data.sys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DbSysAppExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public DbSysAppExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppOidIsNull() {
            addCriterion("APP_OID is null");
            return (Criteria) this;
        }

        public Criteria andAppOidIsNotNull() {
            addCriterion("APP_OID is not null");
            return (Criteria) this;
        }

        public Criteria andAppOidEqualTo(String value) {
            addCriterion("APP_OID =", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidNotEqualTo(String value) {
            addCriterion("APP_OID <>", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidGreaterThan(String value) {
            addCriterion("APP_OID >", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidGreaterThanOrEqualTo(String value) {
            addCriterion("APP_OID >=", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidLessThan(String value) {
            addCriterion("APP_OID <", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidLessThanOrEqualTo(String value) {
            addCriterion("APP_OID <=", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidLike(String value) {
            addCriterion("APP_OID like", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidNotLike(String value) {
            addCriterion("APP_OID not like", value, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidIn(List<String> values) {
            addCriterion("APP_OID in", values, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidNotIn(List<String> values) {
            addCriterion("APP_OID not in", values, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidBetween(String value1, String value2) {
            addCriterion("APP_OID between", value1, value2, "appOid");
            return (Criteria) this;
        }

        public Criteria andAppOidNotBetween(String value1, String value2) {
            addCriterion("APP_OID not between", value1, value2, "appOid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNull() {
            addCriterion("DISPLAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNotNull() {
            addCriterion("DISPLAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameEqualTo(String value) {
            addCriterion("DISPLAY_NAME =", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotEqualTo(String value) {
            addCriterion("DISPLAY_NAME <>", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThan(String value) {
            addCriterion("DISPLAY_NAME >", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME >=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThan(String value) {
            addCriterion("DISPLAY_NAME <", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME <=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLike(String value) {
            addCriterion("DISPLAY_NAME like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotLike(String value) {
            addCriterion("DISPLAY_NAME not like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIn(List<String> values) {
            addCriterion("DISPLAY_NAME in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotIn(List<String> values) {
            addCriterion("DISPLAY_NAME not in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME not between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrIsNull() {
            addCriterion("ACCESS_ROOT_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrIsNotNull() {
            addCriterion("ACCESS_ROOT_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrEqualTo(String value) {
            addCriterion("ACCESS_ROOT_ADDR =", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrNotEqualTo(String value) {
            addCriterion("ACCESS_ROOT_ADDR <>", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrGreaterThan(String value) {
            addCriterion("ACCESS_ROOT_ADDR >", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ACCESS_ROOT_ADDR >=", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrLessThan(String value) {
            addCriterion("ACCESS_ROOT_ADDR <", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrLessThanOrEqualTo(String value) {
            addCriterion("ACCESS_ROOT_ADDR <=", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrLike(String value) {
            addCriterion("ACCESS_ROOT_ADDR like", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrNotLike(String value) {
            addCriterion("ACCESS_ROOT_ADDR not like", value, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrIn(List<String> values) {
            addCriterion("ACCESS_ROOT_ADDR in", values, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrNotIn(List<String> values) {
            addCriterion("ACCESS_ROOT_ADDR not in", values, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrBetween(String value1, String value2) {
            addCriterion("ACCESS_ROOT_ADDR between", value1, value2, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andAccessRootAddrNotBetween(String value1, String value2) {
            addCriterion("ACCESS_ROOT_ADDR not between", value1, value2, "accessRootAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrIsNull() {
            addCriterion("LOGIN_SUCCESS_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrIsNotNull() {
            addCriterion("LOGIN_SUCCESS_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrEqualTo(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR =", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrNotEqualTo(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR <>", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrGreaterThan(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR >", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR >=", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrLessThan(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR <", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR <=", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrLike(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR like", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrNotLike(String value) {
            addCriterion("LOGIN_SUCCESS_ADDR not like", value, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrIn(List<String> values) {
            addCriterion("LOGIN_SUCCESS_ADDR in", values, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrNotIn(List<String> values) {
            addCriterion("LOGIN_SUCCESS_ADDR not in", values, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrBetween(String value1, String value2) {
            addCriterion("LOGIN_SUCCESS_ADDR between", value1, value2, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andLoginSuccessAddrNotBetween(String value1, String value2) {
            addCriterion("LOGIN_SUCCESS_ADDR not between", value1, value2, "loginSuccessAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrIsNull() {
            addCriterion("REMOTE_REGISTRY_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrIsNotNull() {
            addCriterion("REMOTE_REGISTRY_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrEqualTo(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR =", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrNotEqualTo(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR <>", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrGreaterThan(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR >", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrGreaterThanOrEqualTo(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR >=", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrLessThan(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR <", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrLessThanOrEqualTo(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR <=", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrLike(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR like", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrNotLike(String value) {
            addCriterion("REMOTE_REGISTRY_ADDR not like", value, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrIn(List<String> values) {
            addCriterion("REMOTE_REGISTRY_ADDR in", values, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrNotIn(List<String> values) {
            addCriterion("REMOTE_REGISTRY_ADDR not in", values, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrBetween(String value1, String value2) {
            addCriterion("REMOTE_REGISTRY_ADDR between", value1, value2, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andRemoteRegistryAddrNotBetween(String value1, String value2) {
            addCriterion("REMOTE_REGISTRY_ADDR not between", value1, value2, "remoteRegistryAddr");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andIsOtherIsNull() {
            addCriterion("IS_OTHER is null");
            return (Criteria) this;
        }

        public Criteria andIsOtherIsNotNull() {
            addCriterion("IS_OTHER is not null");
            return (Criteria) this;
        }

        public Criteria andIsOtherEqualTo(Integer value) {
            addCriterion("IS_OTHER =", value, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherNotEqualTo(Integer value) {
            addCriterion("IS_OTHER <>", value, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherGreaterThan(Integer value) {
            addCriterion("IS_OTHER >", value, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_OTHER >=", value, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherLessThan(Integer value) {
            addCriterion("IS_OTHER <", value, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherLessThanOrEqualTo(Integer value) {
            addCriterion("IS_OTHER <=", value, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherIn(List<Integer> values) {
            addCriterion("IS_OTHER in", values, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherNotIn(List<Integer> values) {
            addCriterion("IS_OTHER not in", values, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherBetween(Integer value1, Integer value2) {
            addCriterion("IS_OTHER between", value1, value2, "isOther");
            return (Criteria) this;
        }

        public Criteria andIsOtherNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_OTHER not between", value1, value2, "isOther");
            return (Criteria) this;
        }

        public Criteria andIconNameIsNull() {
            addCriterion("ICON_NAME is null");
            return (Criteria) this;
        }

        public Criteria andIconNameIsNotNull() {
            addCriterion("ICON_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andIconNameEqualTo(String value) {
            addCriterion("ICON_NAME =", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameNotEqualTo(String value) {
            addCriterion("ICON_NAME <>", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameGreaterThan(String value) {
            addCriterion("ICON_NAME >", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameGreaterThanOrEqualTo(String value) {
            addCriterion("ICON_NAME >=", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameLessThan(String value) {
            addCriterion("ICON_NAME <", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameLessThanOrEqualTo(String value) {
            addCriterion("ICON_NAME <=", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameLike(String value) {
            addCriterion("ICON_NAME like", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameNotLike(String value) {
            addCriterion("ICON_NAME not like", value, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameIn(List<String> values) {
            addCriterion("ICON_NAME in", values, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameNotIn(List<String> values) {
            addCriterion("ICON_NAME not in", values, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameBetween(String value1, String value2) {
            addCriterion("ICON_NAME between", value1, value2, "iconName");
            return (Criteria) this;
        }

        public Criteria andIconNameNotBetween(String value1, String value2) {
            addCriterion("ICON_NAME not between", value1, value2, "iconName");
            return (Criteria) this;
        }

        public Criteria andParentOidIsNull() {
            addCriterion("PARENT_OID is null");
            return (Criteria) this;
        }

        public Criteria andParentOidIsNotNull() {
            addCriterion("PARENT_OID is not null");
            return (Criteria) this;
        }

        public Criteria andParentOidEqualTo(String value) {
            addCriterion("PARENT_OID =", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotEqualTo(String value) {
            addCriterion("PARENT_OID <>", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidGreaterThan(String value) {
            addCriterion("PARENT_OID >", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_OID >=", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidLessThan(String value) {
            addCriterion("PARENT_OID <", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidLessThanOrEqualTo(String value) {
            addCriterion("PARENT_OID <=", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidLike(String value) {
            addCriterion("PARENT_OID like", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotLike(String value) {
            addCriterion("PARENT_OID not like", value, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidIn(List<String> values) {
            addCriterion("PARENT_OID in", values, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotIn(List<String> values) {
            addCriterion("PARENT_OID not in", values, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidBetween(String value1, String value2) {
            addCriterion("PARENT_OID between", value1, value2, "parentOid");
            return (Criteria) this;
        }

        public Criteria andParentOidNotBetween(String value1, String value2) {
            addCriterion("PARENT_OID not between", value1, value2, "parentOid");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("SORT is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("SORT =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("SORT <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("SORT >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("SORT <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("SORT <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("SORT in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("SORT not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("SORT between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andIsAbleIsNull() {
            addCriterion("IS_ABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsAbleIsNotNull() {
            addCriterion("IS_ABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsAbleEqualTo(Integer value) {
            addCriterion("IS_ABLE =", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleNotEqualTo(Integer value) {
            addCriterion("IS_ABLE <>", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleGreaterThan(Integer value) {
            addCriterion("IS_ABLE >", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_ABLE >=", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleLessThan(Integer value) {
            addCriterion("IS_ABLE <", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleLessThanOrEqualTo(Integer value) {
            addCriterion("IS_ABLE <=", value, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleIn(List<Integer> values) {
            addCriterion("IS_ABLE in", values, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleNotIn(List<Integer> values) {
            addCriterion("IS_ABLE not in", values, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleBetween(Integer value1, Integer value2) {
            addCriterion("IS_ABLE between", value1, value2, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsAbleNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_ABLE not between", value1, value2, "isAble");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_app
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_app
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}