package com.zfsoft.microservice.platform.dbaccess.data.sys;

import java.util.Date;

public class DbSysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.APP_OID
     *
     * @mbggenerated
     */
    private String appOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.PERMISSION_OID
     *
     * @mbggenerated
     */
    private String permissionOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.IS_FRAME
     *
     * @mbggenerated
     */
    private Integer isFrame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.ROUTER
     *
     * @mbggenerated
     */
    private String router;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.HYPER_LINK
     *
     * @mbggenerated
     */
    private String hyperLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.STR
     *
     * @mbggenerated
     */
    private String str;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.PARENT_OID
     *
     * @mbggenerated
     */
    private String parentOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.IS_ABLE
     *
     * @mbggenerated
     */
    private Integer isAble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.FUNCTION_TYPE
     *
     * @mbggenerated
     */
    private String functionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.ICON_NAME
     *
     * @mbggenerated
     */
    private String iconName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.PER_LEVEL
     *
     * @mbggenerated
     */
    private Integer perLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_permission.OUT_LINK
     *
     * @mbggenerated
     */
    private String outLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.ID
     *
     * @return the value of t_sys_permission.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.ID
     *
     * @param id the value for t_sys_permission.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.APP_OID
     *
     * @return the value of t_sys_permission.APP_OID
     *
     * @mbggenerated
     */
    public String getAppOid() {
        return appOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.APP_OID
     *
     * @param appOid the value for t_sys_permission.APP_OID
     *
     * @mbggenerated
     */
    public void setAppOid(String appOid) {
        this.appOid = appOid == null ? null : appOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.PERMISSION_OID
     *
     * @return the value of t_sys_permission.PERMISSION_OID
     *
     * @mbggenerated
     */
    public String getPermissionOid() {
        return permissionOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.PERMISSION_OID
     *
     * @param permissionOid the value for t_sys_permission.PERMISSION_OID
     *
     * @mbggenerated
     */
    public void setPermissionOid(String permissionOid) {
        this.permissionOid = permissionOid == null ? null : permissionOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.NAME
     *
     * @return the value of t_sys_permission.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.NAME
     *
     * @param name the value for t_sys_permission.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.IS_FRAME
     *
     * @return the value of t_sys_permission.IS_FRAME
     *
     * @mbggenerated
     */
    public Integer getIsFrame() {
        return isFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.IS_FRAME
     *
     * @param isFrame the value for t_sys_permission.IS_FRAME
     *
     * @mbggenerated
     */
    public void setIsFrame(Integer isFrame) {
        this.isFrame = isFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.ROUTER
     *
     * @return the value of t_sys_permission.ROUTER
     *
     * @mbggenerated
     */
    public String getRouter() {
        return router;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.ROUTER
     *
     * @param router the value for t_sys_permission.ROUTER
     *
     * @mbggenerated
     */
    public void setRouter(String router) {
        this.router = router == null ? null : router.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.HYPER_LINK
     *
     * @return the value of t_sys_permission.HYPER_LINK
     *
     * @mbggenerated
     */
    public String getHyperLink() {
        return hyperLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.HYPER_LINK
     *
     * @param hyperLink the value for t_sys_permission.HYPER_LINK
     *
     * @mbggenerated
     */
    public void setHyperLink(String hyperLink) {
        this.hyperLink = hyperLink == null ? null : hyperLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.STR
     *
     * @return the value of t_sys_permission.STR
     *
     * @mbggenerated
     */
    public String getStr() {
        return str;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.STR
     *
     * @param str the value for t_sys_permission.STR
     *
     * @mbggenerated
     */
    public void setStr(String str) {
        this.str = str == null ? null : str.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.PARENT_OID
     *
     * @return the value of t_sys_permission.PARENT_OID
     *
     * @mbggenerated
     */
    public String getParentOid() {
        return parentOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.PARENT_OID
     *
     * @param parentOid the value for t_sys_permission.PARENT_OID
     *
     * @mbggenerated
     */
    public void setParentOid(String parentOid) {
        this.parentOid = parentOid == null ? null : parentOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.MEMO
     *
     * @return the value of t_sys_permission.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.MEMO
     *
     * @param memo the value for t_sys_permission.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.IS_ABLE
     *
     * @return the value of t_sys_permission.IS_ABLE
     *
     * @mbggenerated
     */
    public Integer getIsAble() {
        return isAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.IS_ABLE
     *
     * @param isAble the value for t_sys_permission.IS_ABLE
     *
     * @mbggenerated
     */
    public void setIsAble(Integer isAble) {
        this.isAble = isAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.IS_DELETE
     *
     * @return the value of t_sys_permission.IS_DELETE
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.IS_DELETE
     *
     * @param isDelete the value for t_sys_permission.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.SORT
     *
     * @return the value of t_sys_permission.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.SORT
     *
     * @param sort the value for t_sys_permission.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.FUNCTION_TYPE
     *
     * @return the value of t_sys_permission.FUNCTION_TYPE
     *
     * @mbggenerated
     */
    public String getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.FUNCTION_TYPE
     *
     * @param functionType the value for t_sys_permission.FUNCTION_TYPE
     *
     * @mbggenerated
     */
    public void setFunctionType(String functionType) {
        this.functionType = functionType == null ? null : functionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.ICON_NAME
     *
     * @return the value of t_sys_permission.ICON_NAME
     *
     * @mbggenerated
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.ICON_NAME
     *
     * @param iconName the value for t_sys_permission.ICON_NAME
     *
     * @mbggenerated
     */
    public void setIconName(String iconName) {
        this.iconName = iconName == null ? null : iconName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.CODE
     *
     * @return the value of t_sys_permission.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.CODE
     *
     * @param code the value for t_sys_permission.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.PER_LEVEL
     *
     * @return the value of t_sys_permission.PER_LEVEL
     *
     * @mbggenerated
     */
    public Integer getPerLevel() {
        return perLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.PER_LEVEL
     *
     * @param perLevel the value for t_sys_permission.PER_LEVEL
     *
     * @mbggenerated
     */
    public void setPerLevel(Integer perLevel) {
        this.perLevel = perLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.MODIFY_DATE
     *
     * @return the value of t_sys_permission.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.MODIFY_DATE
     *
     * @param modifyDate the value for t_sys_permission.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_permission.OUT_LINK
     *
     * @return the value of t_sys_permission.OUT_LINK
     *
     * @mbggenerated
     */
    public String getOutLink() {
        return outLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_permission.OUT_LINK
     *
     * @param outLink the value for t_sys_permission.OUT_LINK
     *
     * @mbggenerated
     */
    public void setOutLink(String outLink) {
        this.outLink = outLink == null ? null : outLink.trim();
    }
}