package com.zfsoft.ha.dbaccess.dao;

import com.zfsoft.ha.dbaccess.data.DbHaPerformancePhoneRecord;
import com.zfsoft.ha.dbaccess.data.example.DbHaPerformancePhoneRecordExample;
import com.zfsoft.ha.dbaccess.data.vo.DbHaPerformanceAppraisalStatisticVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface DbHaPerformancePhoneRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    long countByExample(DbHaPerformancePhoneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    int deleteByExample(DbHaPerformancePhoneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    int insert(DbHaPerformancePhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    int insertSelective(DbHaPerformancePhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    List<DbHaPerformancePhoneRecord> selectByExample(DbHaPerformancePhoneRecordExample example);

    DbHaPerformancePhoneRecord queryById(Long id);

    DbHaPerformancePhoneRecord selectByPhoneAndCallTime(String phone, Date callTime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbHaPerformancePhoneRecord record, @Param("example") DbHaPerformancePhoneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_performance_phone_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbHaPerformancePhoneRecord record, @Param("example") DbHaPerformancePhoneRecordExample example);

    DbHaPerformanceAppraisalStatisticVo getPhoneDuration(String cloudServiceNumber, String beginTime, String endTime);
}