package com.zfsoft.ha.dbaccess.dao;

import com.zfsoft.ha.dbaccess.data.DbHaPlusProject;
import com.zfsoft.ha.dbaccess.data.example.DbHaPlusProjectExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DbHaPlusProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    long countByExample(DbHaPlusProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int deleteByExample(DbHaPlusProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int insert(DbHaPlusProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int insertSelective(DbHaPlusProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    List<DbHaPlusProject> selectByExample(DbHaPlusProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    DbHaPlusProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbHaPlusProject record, @Param("example") DbHaPlusProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbHaPlusProject record, @Param("example") DbHaPlusProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbHaPlusProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_plus_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbHaPlusProject record);
}