package com.zfsoft.ha.dbaccess.dao;

import com.zfsoft.ha.dbaccess.data.DbHaWorkUserSchedule;
import com.zfsoft.ha.dbaccess.data.example.DbHaWorkUserScheduleExample;

import java.util.Date;
import java.util.List;

import com.zfsoft.ha.dbaccess.data.vo.DbHaWorkUserScheduleVo;
import com.zfsoft.ha.dbaccess.data.vo.DbHaWorkUserSchedule_AppVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import javax.xml.crypto.dsig.spec.XSLTTransformParameterSpec;

@Mapper
public interface DbHaWorkUserScheduleMapper {
    /**
     *  获取帮办服务人数
     */
    Integer countWorkUsers(Date workDate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    long countByExample(DbHaWorkUserScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int deleteByExample(DbHaWorkUserScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int insert(DbHaWorkUserSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int insertSelective(DbHaWorkUserSchedule record);

    @Select({"select count(*) from t_ha_work_user_schedule where `YEAR_MONTH`= #{yearMonth} limit 1"})
    int countByYearMonthAfter(String yearMonth);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    List<DbHaWorkUserSchedule> selectByExample(DbHaWorkUserScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    DbHaWorkUserSchedule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbHaWorkUserSchedule record, @Param("example") DbHaWorkUserScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbHaWorkUserSchedule record, @Param("example") DbHaWorkUserScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbHaWorkUserSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbHaWorkUserSchedule record);

    /**
     * 根据年月，小组id，帮办人员名称（模糊）查询排班信息
     * @param yearMonth 年月
     * @param groupId 小组id
     * @param workUserName 帮办人员名称
     * @return
     */
    List<DbHaWorkUserScheduleVo> queryScheduleList(String yearMonth, Long groupId, String workUserName);

    /**
     * 根据年月，帮办人员id 查询排班信息
     * @param yearMonth 年月
     * @param workUserId 帮办id
     * @return
     */
    List<DbHaWorkUserSchedule> queryList(String yearMonth, Long workUserId);

    /**
     * 获取帮办人员的七天排班和预约状态
     * @param workUserId 帮办id
     * @param startDate 开始时间
     * @param endDate 结束时间
     * @param scheduleId 指定排班id查询当天预约情况
     */
    List<DbHaWorkUserSchedule_AppVo> queryScheAppList(Long workUserId, String startDate, String endDate,Long scheduleId );


    List<DbHaWorkUserScheduleVo> queryListByDayAndGroupidAndScheduleStatus(Date workDate, String groupId, String haType, String apm);

    List<DbHaWorkUserScheduleVo> queryUserScheAndQueueListByDay(Date workDate, String groupId, String haType, String apm,Date beginADay, Date endADay);

}
