package com.zfsoft.ha.dbaccess.dao;

import com.zfsoft.ha.dbaccess.data.DbHaWorkGroupSplit;
import com.zfsoft.ha.dbaccess.data.example.DbHaWorkGroupSplitExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DbHaWorkGroupSplitMapper {

    /**
     * 根据id查询分组表信息
     */
    DbHaWorkGroupSplit queryById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    long countByExample(DbHaWorkGroupSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    int deleteByExample(DbHaWorkGroupSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    int insert(DbHaWorkGroupSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    int insertSelective(DbHaWorkGroupSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    List<DbHaWorkGroupSplit> selectByExample(DbHaWorkGroupSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbHaWorkGroupSplit record, @Param("example") DbHaWorkGroupSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_work_user_group_split
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbHaWorkGroupSplit record, @Param("example") DbHaWorkGroupSplitExample example);
}