package com.zfsoft.ha.dbaccess.dao;

import com.zfsoft.ha.dbaccess.data.DbHaVideoAccess;
import com.zfsoft.ha.dbaccess.data.example.DbHaVideoAccessExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
@Mapper
public interface DbHaVideoAccessMapper {
    DbHaVideoAccess selectByWorkUserId(Long workUserId, Date startTime, Date endTime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    long countByExample(DbHaVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int deleteByExample(DbHaVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int insert(DbHaVideoAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int insertSelective(DbHaVideoAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    List<DbHaVideoAccess> selectByExample(DbHaVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    DbHaVideoAccess selectByPrimaryKey(Long id);

    DbHaVideoAccess selectByRoomIdAndWorkUserId(Long roomOid,Long workUserId,String existStatus);

    List<DbHaVideoAccess> selectIsHaveNewCall(Long workUserId, String existStatus, Date startTime, Date endTime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbHaVideoAccess record, @Param("example") DbHaVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbHaVideoAccess record, @Param("example") DbHaVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbHaVideoAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_access
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbHaVideoAccess record);

    List<DbHaVideoAccess> selectListByRoomId(Long roomId, Date roomUpdateDate);
}
