package com.zfsoft.ha.dbaccess.dao;

import com.zfsoft.ha.dbaccess.data.DbHaVideoRoom;
import com.zfsoft.ha.dbaccess.data.example.DbHaVideoRoomExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.Date;
import java.util.List;
@Mapper
public interface DbHaVideoRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    long countByExample(DbHaVideoRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int deleteByExample(DbHaVideoRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int insert(DbHaVideoRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int insertSelective(DbHaVideoRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    List<DbHaVideoRoom> selectByExample(DbHaVideoRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    DbHaVideoRoom selectByPrimaryKey(Long id);

    /**
     * 通过queueId查询单条数据
     *
     * @param queueId 主键
     * @return 实例对象
     */
    DbHaVideoRoom selectByQueueId(Long queueId);
    /**
     * 通过房间号查询单条数据
     *
     * @param roomNumber 房间号
     * @return 实例对象
     */
    DbHaVideoRoom selectRoomNum(String roomNumber);
    /**
     * 通过ID查询单条数据
     *
     * @param id 主键
     * @return 实例对象
     */
    DbHaVideoRoom queryById(Long id);

    /**
     * 加入房间，正在房间人数和房间最大人数加一
     * @param roomId
     * @return
     */
    @Update({"UPDATE t_ha_video_room SET PEAK_NUM=PEAK_NUM +1 , ROOM_NUM=ROOM_NUM+1 WHERE ID=#{roomId}"})
    int addNumbById(Long roomId);

    /**
     * 退出房间，正在房间人数减一
     * @param roomId
     * @return
     */
    @Update({"UPDATE t_ha_video_room SET  ROOM_NUM=ROOM_NUM-1 WHERE ID=#{roomId}"})
    int subNumbById(Long roomId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbHaVideoRoom record, @Param("example") DbHaVideoRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbHaVideoRoom record, @Param("example") DbHaVideoRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbHaVideoRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ha_video_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbHaVideoRoom record);

    /**
     * 查询当前开启的视频帮办的信息
     * @param workUserId 当前视频用户id
     * @param roomStatus 房间状态
     * @param existStatus 出入记录状态
     * @param beginDate  开始时间
     * @param endDate  结束时间
     * @return
     */
    List<DbHaVideoRoom> selectBySponsorAndStatus(String workUserId, String roomStatus,
                                                 String existStatus, Date beginDate, Date endDate);
}
