package com.zfsoft.superwindow.data.yxpz;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class HumanEvidenceDeviceMgt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.HUMAN_EVIDENCE_DEVICE_MGT_OID
     *
     * @mbggenerated
     */
    private String humanEvidenceDeviceMgtOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.SALT
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.IP_ADDRESS
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.MAC_ADDRESS
     *
     * @mbggenerated
     */
    private String macAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.DEVICE_ID
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.BINDING_WINDOW
     *
     * @mbggenerated
     */
    private String bindingWindow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_human_evidence_device_mgt.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * 绑定窗口编号
     */
    private String bindingWindowNum;

    /**
     * 区划id
     */
    private String districtOid;

    /**
     * 机构id
     */
    private String organOid;

}