package com.zfsoft.superwindow.data.yxpz;

import lombok.*;

import java.util.Date;

/**
 * @author: kkfan
 * @create: 2020-10-22 15:09:01
 * @description: 站点区划对应关系表
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SysSiteDistrictRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.SYS_SITE_DISTRICT_RELATION_OID
     *
     * @mbggenerated
     */
    private String sysSiteDistrictRelationOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.SYS_AREA_SITE_OID
     *
     * @mbggenerated
     */
    private String sysAreaSiteOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.DISTRICT_OID
     *
     * @mbggenerated
     */
    private String districtOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_site_district_relation.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

}
