package com.zfsoft.service.sxService.data;

import lombok.Data;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
public class SxMaterialFormTemp {

    /**
     * 主键
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * 业务主键
     *
     * @mbg.generated
     */
    private String oid;

    /**
     * 材料主键
     *
     * @mbg.generated
     */
    private String materialOid;

    /**
     * 事项主键
     *
     * @mbg.generated
     */
    private String serviceOid;

    /**
     * 表单编码
     *
     * @mbg.generated
     */
    private String formCode;

    /**
     * 模板主键
     *
     * @mbg.generated
     */
    private String templateOid;

    /**
     * 模板名称
     *
     * @mbg.generated
     */
    private String templateName;

    /**
     * 是否删除
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     * 创建时间
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * 修改时间
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.SEAL_URL
     *
     * @mbg.generated
     */
    private String sealUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.TEMPLATE_URL
     *
     * @mbg.generated
     */
    private String templateUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.SEAL_STATUS
     *
     * @mbg.generated
     */
    private Integer sealStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_form_template.DESIGN_OID
     *
     * @mbg.generated
     */
    private String designOid;

    private String madeMaterialType;

    private String materialName;
}
