package com.zfsoft.single.data.ywbl;
import lombok.*;

import java.util.Date;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CaseMaterialOutOfStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.OUT_OID
     *
     * @mbggenerated
     */
    private String outOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.REG_OID
     *
     * @mbggenerated
     */
    private String regOid;

    private String serviceOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.CASE_NUMBER
     *
     * @mbggenerated
     */
    private String caseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.APPLY_USER_NAME
     *
     * @mbggenerated
     */
    private String applyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.SERVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    private String serviceTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.CARD_NUMBER
     *
     * @mbggenerated
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.CASE_CREATE_DATE
     *
     * @mbggenerated
     */
    private Date caseCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.MATERIAL_OIDS
     *
     * @mbggenerated
     */
    private String materialOids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.OUT_STATUS
     *
     * @mbggenerated
     */
    private String outStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.OUT_STOCK_DATE
     *
     * @mbggenerated
     */
    private Date outStockDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.OUT_STOCK_USER
     *
     * @mbggenerated
     */
    private String outStockUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.OUT_USER_NAME
     *
     * @mbggenerated
     */
    private String outUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_case_material_out_of_stock.CASE_CREATE_USER_OID
     *
     * @mbggenerated
     */
    private String caseCreateUserOid;

    /**
     出库方式 1、现场领取 2、快递送达
     */
    private Integer outType;

    /**
     领件人名称
     */
    private String receiverName;

    /**
     领件人手机
     */
    private String receiverPhone;

    /**
    快递公司
     */
    private String kdCompany;

    /**
    快递编号
     */
    private String kdCode;

    /**
     寄件人名称
     */
    private String senderUserName;

    /**寄件人手机
     */
    private String senderUserPhone;

    //身份证号码
    private String idCard;
    //出库材料名称（仅作展示用）
    private String materialNameOut;

    /**
     *开始时间
     */
    private String startDate;

    /**
     *结束时间
     */
    private String endDate;

    private List serviceOids;

    private String selectMaterialOids;

    private String outAttaOid;
    private String sdAttaOid;

    private String serviceName;

    private   List<CaseMaterialOutOfStockRecord> caseMaterialOutOfStockRecordList;

}
