package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbAdvisoryRegistration;
import com.zfsoft.superwindow.dbaccess.data.DbAdvisoryRegistrationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DbAdvisoryRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int countByExample(DbAdvisoryRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int deleteByExample(DbAdvisoryRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int insert(DbAdvisoryRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int insertSelective(DbAdvisoryRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    List<DbAdvisoryRegistration> selectByExample(DbAdvisoryRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    DbAdvisoryRegistration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbAdvisoryRegistration record, @Param("example") DbAdvisoryRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbAdvisoryRegistration record, @Param("example") DbAdvisoryRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbAdvisoryRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advisory_registration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbAdvisoryRegistration record);
}