package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbAfterAdvisory;
import com.zfsoft.superwindow.dbaccess.data.DbAfterAdvisoryExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DbAfterAdvisoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int countByExample(DbAfterAdvisoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int deleteByExample(DbAfterAdvisoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int insert(DbAfterAdvisory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int insertSelective(DbAfterAdvisory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    List<DbAfterAdvisory> selectByExample(DbAfterAdvisoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    DbAfterAdvisory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbAfterAdvisory record, @Param("example") DbAfterAdvisoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbAfterAdvisory record, @Param("example") DbAfterAdvisoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbAfterAdvisory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_after_advisory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbAfterAdvisory record);
}