package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbCardCatalogue;
import com.zfsoft.superwindow.dbaccess.data.DbCardCatalogueExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DbCardCatalogueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int countByExample(DbCardCatalogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int deleteByExample(DbCardCatalogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int insert(DbCardCatalogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int insertSelective(DbCardCatalogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    List<DbCardCatalogue> selectByExample(DbCardCatalogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    DbCardCatalogue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbCardCatalogue record, @Param("example") DbCardCatalogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbCardCatalogue record, @Param("example") DbCardCatalogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbCardCatalogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_catalogue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbCardCatalogue record);

    /***
     * @Description:  根据业务主键查询
     * @Author:liangss
     * @Date:2021/11/4
     * @Param: [oid]
     */
    DbCardCatalogue getCardCatalogueByOid(String oid);

    /***
     * @Description:  根据业务主键删除
     * @Author:liangss
     * @Date:2021/11/4
     * @Param: [oid]
     */
    void deleteByOid(String oid);

    /***
     * @Description: 查询卡证目录全部列表
     * @Author:liangss
     * @Date:2021/11/5
     * @Param: []
     */
    List<DbCardCatalogue> getAllCardCatalogueList();
}