package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbHumanEvidenceDeviceMgt;
import com.zfsoft.superwindow.dbaccess.data.DbHumanEvidenceDeviceMgtExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DbHumanEvidenceDeviceMgtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int countByExample(DbHumanEvidenceDeviceMgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int deleteByExample(DbHumanEvidenceDeviceMgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int insert(DbHumanEvidenceDeviceMgt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int insertSelective(DbHumanEvidenceDeviceMgt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    List<DbHumanEvidenceDeviceMgt> selectByExample(DbHumanEvidenceDeviceMgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    DbHumanEvidenceDeviceMgt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbHumanEvidenceDeviceMgt record, @Param("example") DbHumanEvidenceDeviceMgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbHumanEvidenceDeviceMgt record, @Param("example") DbHumanEvidenceDeviceMgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbHumanEvidenceDeviceMgt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_human_evidence_device_mgt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbHumanEvidenceDeviceMgt record);

    /**
     * 查询列表
     * @param record
     * @return
     */
    List<DbHumanEvidenceDeviceMgt> queryDbHumanEvidenceDeviceMgtList(DbHumanEvidenceDeviceMgt record);
}