package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbInterApiResponse;
import com.zfsoft.superwindow.dbaccess.data.DbInterApiResponseExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DbInterApiResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    long countByExample(DbInterApiResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int deleteByExample(DbInterApiResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int insert(DbInterApiResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int insertSelective(DbInterApiResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    List<DbInterApiResponse> selectByExample(DbInterApiResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    DbInterApiResponse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbInterApiResponse record, @Param("example") DbInterApiResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbInterApiResponse record, @Param("example") DbInterApiResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbInterApiResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inter_api_response
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbInterApiResponse record);
}