package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbStampRecord;
import com.zfsoft.superwindow.dbaccess.data.DbStampRecordExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DbStampRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int countByExample(DbStampRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int deleteByExample(DbStampRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int insert(DbStampRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int insertSelective(DbStampRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    List<DbStampRecord> selectByExample(DbStampRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    DbStampRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbStampRecord record, @Param("example") DbStampRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbStampRecord record, @Param("example") DbStampRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbStampRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ahs_stamp_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbStampRecord record);


    DbStampRecord getCaseFileAttaRecByOidAndCataOid(String attaOid, String cataOid);
}