package com.zfsoft.superwindow.dbaccess.dao;

import com.zfsoft.superwindow.dbaccess.data.DbSysSiteDistrictRelation;
import com.zfsoft.superwindow.dbaccess.data.DbSysSiteDistrictRelationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface DbSysSiteDistrictRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int countByExample(DbSysSiteDistrictRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int deleteByExample(DbSysSiteDistrictRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int insert(DbSysSiteDistrictRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int insertSelective(DbSysSiteDistrictRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    List<DbSysSiteDistrictRelation> selectByExample(DbSysSiteDistrictRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    DbSysSiteDistrictRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbSysSiteDistrictRelation record, @Param("example") DbSysSiteDistrictRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbSysSiteDistrictRelation record, @Param("example") DbSysSiteDistrictRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbSysSiteDistrictRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_site_district_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbSysSiteDistrictRelation record);

    /*
     * @Description:根据区划OID获取辖区列表
     * @Author: wangxl
     * @Date: 2020/12/18 14:34
     * @param paramRelMap:
     * @return: java.util.List<com.zfsoft.dbaccess.data.DbSysSiteDistrictRelation>
     **/
    List<DbSysSiteDistrictRelation> querySiteDistrictRelByDistOid(Map<String, Object> paramRelMap);

}