package com.zfsoft.service.dbaccess.data.sxSituation;

import java.util.Date;

public class DbSxServiceSituation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.OID
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.SITUATION_NAME
     *
     * @mbggenerated
     */
    private String situationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.SERVICE_OID
     *
     * @mbggenerated
     */
    private String serviceOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.SORT
     *
     * @mbggenerated
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_service_situation.DELETE_STATUS
     *
     * @mbggenerated
     */
    private Short deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.OID
     *
     * @return the value of t_sx_service_situation.OID
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.OID
     *
     * @param oid the value for t_sx_service_situation.OID
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.ID
     *
     * @return the value of t_sx_service_situation.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.ID
     *
     * @param id the value for t_sx_service_situation.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.SITUATION_NAME
     *
     * @return the value of t_sx_service_situation.SITUATION_NAME
     *
     * @mbggenerated
     */
    public String getSituationName() {
        return situationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.SITUATION_NAME
     *
     * @param situationName the value for t_sx_service_situation.SITUATION_NAME
     *
     * @mbggenerated
     */
    public void setSituationName(String situationName) {
        this.situationName = situationName == null ? null : situationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.SERVICE_OID
     *
     * @return the value of t_sx_service_situation.SERVICE_OID
     *
     * @mbggenerated
     */
    public String getServiceOid() {
        return serviceOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.SERVICE_OID
     *
     * @param serviceOid the value for t_sx_service_situation.SERVICE_OID
     *
     * @mbggenerated
     */
    public void setServiceOid(String serviceOid) {
        this.serviceOid = serviceOid == null ? null : serviceOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.SORT
     *
     * @return the value of t_sx_service_situation.SORT
     *
     * @mbggenerated
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.SORT
     *
     * @param sort the value for t_sx_service_situation.SORT
     *
     * @mbggenerated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.CREATE_DATE
     *
     * @return the value of t_sx_service_situation.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.CREATE_DATE
     *
     * @param createDate the value for t_sx_service_situation.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.MODIFY_DATE
     *
     * @return the value of t_sx_service_situation.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.MODIFY_DATE
     *
     * @param modifyDate the value for t_sx_service_situation.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_service_situation.DELETE_STATUS
     *
     * @return the value of t_sx_service_situation.DELETE_STATUS
     *
     * @mbggenerated
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_service_situation.DELETE_STATUS
     *
     * @param deleteStatus the value for t_sx_service_situation.DELETE_STATUS
     *
     * @mbggenerated
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}