package com.zfsoft.single.dbaccess.data;

import java.util.Date;

public class DbSxMaterialBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.BILL_OID
     *
     * @mbggenerated
     */
    private String billOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_NAME
     *
     * @mbggenerated
     */
    private String directoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_GENRE
     *
     * @mbggenerated
     */
    private String directoryGenre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_CODE
     *
     * @mbggenerated
     */
    private String directoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_OBJ
     *
     * @mbggenerated
     */
    private String directoryObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_TYPE
     *
     * @mbggenerated
     */
    private Integer directoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_CODE_PRE
     *
     * @mbggenerated
     */
    private String directoryCodePre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DIRECTORY_CODE_POS
     *
     * @mbggenerated
     */
    private Integer directoryCodePos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.DEPARTMENT_TYPE
     *
     * @mbggenerated
     */
    private String departmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sx_material_bill.service_oid
     *
     * @mbggenerated
     */
    private String serviceOid;


    private String directoryStatus;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.ID
     *
     * @return the value of t_sx_material_bill.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.ID
     *
     * @param id the value for t_sx_material_bill.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.BILL_OID
     *
     * @return the value of t_sx_material_bill.BILL_OID
     *
     * @mbggenerated
     */
    public String getBillOid() {
        return billOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.BILL_OID
     *
     * @param billOid the value for t_sx_material_bill.BILL_OID
     *
     * @mbggenerated
     */
    public void setBillOid(String billOid) {
        this.billOid = billOid == null ? null : billOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_NAME
     *
     * @return the value of t_sx_material_bill.DIRECTORY_NAME
     *
     * @mbggenerated
     */
    public String getDirectoryName() {
        return directoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_NAME
     *
     * @param directoryName the value for t_sx_material_bill.DIRECTORY_NAME
     *
     * @mbggenerated
     */
    public void setDirectoryName(String directoryName) {
        this.directoryName = directoryName == null ? null : directoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_GENRE
     *
     * @return the value of t_sx_material_bill.DIRECTORY_GENRE
     *
     * @mbggenerated
     */
    public String getDirectoryGenre() {
        return directoryGenre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_GENRE
     *
     * @param directoryGenre the value for t_sx_material_bill.DIRECTORY_GENRE
     *
     * @mbggenerated
     */
    public void setDirectoryGenre(String directoryGenre) {
        this.directoryGenre = directoryGenre == null ? null : directoryGenre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_CODE
     *
     * @return the value of t_sx_material_bill.DIRECTORY_CODE
     *
     * @mbggenerated
     */
    public String getDirectoryCode() {
        return directoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_CODE
     *
     * @param directoryCode the value for t_sx_material_bill.DIRECTORY_CODE
     *
     * @mbggenerated
     */
    public void setDirectoryCode(String directoryCode) {
        this.directoryCode = directoryCode == null ? null : directoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_OBJ
     *
     * @return the value of t_sx_material_bill.DIRECTORY_OBJ
     *
     * @mbggenerated
     */
    public String getDirectoryObj() {
        return directoryObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_OBJ
     *
     * @param directoryObj the value for t_sx_material_bill.DIRECTORY_OBJ
     *
     * @mbggenerated
     */
    public void setDirectoryObj(String directoryObj) {
        this.directoryObj = directoryObj == null ? null : directoryObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.IS_DELETE
     *
     * @return the value of t_sx_material_bill.IS_DELETE
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.IS_DELETE
     *
     * @param isDelete the value for t_sx_material_bill.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.CREATE_DATE
     *
     * @return the value of t_sx_material_bill.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.CREATE_DATE
     *
     * @param createDate the value for t_sx_material_bill.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_TYPE
     *
     * @return the value of t_sx_material_bill.DIRECTORY_TYPE
     *
     * @mbggenerated
     */
    public Integer getDirectoryType() {
        return directoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_TYPE
     *
     * @param directoryType the value for t_sx_material_bill.DIRECTORY_TYPE
     *
     * @mbggenerated
     */
    public void setDirectoryType(Integer directoryType) {
        this.directoryType = directoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_CODE_PRE
     *
     * @return the value of t_sx_material_bill.DIRECTORY_CODE_PRE
     *
     * @mbggenerated
     */
    public String getDirectoryCodePre() {
        return directoryCodePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_CODE_PRE
     *
     * @param directoryCodePre the value for t_sx_material_bill.DIRECTORY_CODE_PRE
     *
     * @mbggenerated
     */
    public void setDirectoryCodePre(String directoryCodePre) {
        this.directoryCodePre = directoryCodePre == null ? null : directoryCodePre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DIRECTORY_CODE_POS
     *
     * @return the value of t_sx_material_bill.DIRECTORY_CODE_POS
     *
     * @mbggenerated
     */
    public Integer getDirectoryCodePos() {
        return directoryCodePos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DIRECTORY_CODE_POS
     *
     * @param directoryCodePos the value for t_sx_material_bill.DIRECTORY_CODE_POS
     *
     * @mbggenerated
     */
    public void setDirectoryCodePos(Integer directoryCodePos) {
        this.directoryCodePos = directoryCodePos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.DEPARTMENT_TYPE
     *
     * @return the value of t_sx_material_bill.DEPARTMENT_TYPE
     *
     * @mbggenerated
     */
    public String getDepartmentType() {
        return departmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.DEPARTMENT_TYPE
     *
     * @param departmentType the value for t_sx_material_bill.DEPARTMENT_TYPE
     *
     * @mbggenerated
     */
    public void setDepartmentType(String departmentType) {
        this.departmentType = departmentType == null ? null : departmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sx_material_bill.service_oid
     *
     * @return the value of t_sx_material_bill.service_oid
     *
     * @mbggenerated
     */
    public String getServiceOid() {
        return serviceOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sx_material_bill.service_oid
     *
     * @param serviceOid the value for t_sx_material_bill.service_oid
     *
     * @mbggenerated
     */
    public void setServiceOid(String serviceOid) {
        this.serviceOid = serviceOid == null ? null : serviceOid.trim();
    }

    public String getDirectoryStatus() {
        return directoryStatus;
    }

    public void setDirectoryStatus(String directoryStatus) {
        this.directoryStatus = directoryStatus;
    }
}