package com.zfsoft.microservice.platform.dbaccess.dao.sys;

import com.zfsoft.microservice.platform.dbaccess.data.sys.DbSysOrgan;
import com.zfsoft.microservice.platform.dbaccess.data.sys.DbSysOrganExample;
import org.apache.ibatis.annotations.*;

import java.util.List;
@Mapper
public interface DbSysOrganMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int countByExample(DbSysOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int deleteByExample(DbSysOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int insert(DbSysOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int insertSelective(DbSysOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    List<DbSysOrgan> selectByExample(DbSysOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    List<DbSysOrgan> selectDbSysOrganExampleByExample(DbSysOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    DbSysOrgan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbSysOrgan record, @Param("example") DbSysOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbSysOrgan record, @Param("example") DbSysOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbSysOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_organ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbSysOrgan record);


    /**
     * @description:  根据业务主键查询实体类
     * @param organOid 业务主键
     * @author: wuxx
     * @Date: 2020/10/28 9:17
     **/
    DbSysOrgan selectByOrganOid(String organOid);


    /**
     * @description:  逻辑删除组织机构
     * @author: wuxx
     * @Date: 2020/9/1 14:23
     **/
    @Update({"update t_sys_organ set IS_DELETE='1' where ID = #{id,jdbcType=BIGINT} "
    })
    int deleteByOid(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dict
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "ID,ORGAN_OID, CODE, NAME, DISTRICT_OID, PARENT_OID, FULL_NAME, SIMPLE_CODE, ADDRESS, ",
            "TELPHONE, ORGAN_OID_PATH, TYPE_DICT_OID, SORT, IS_ABLE, IS_DELETE, UNITE_CODE, MODIFY_DATE, ",
            "DEPT_CODE",
            "from t_sys_organ",
            "where CODE = #{code,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    DbSysOrgan selectByDbSysOrganByCode(String code);

    /**
     * @description: 根据主键获取名称
     * @param organOid 主键
     * @author: wuxx
     * @Date: 2020/11/2 14:56
     **/
    @Select({
            "select NAME from t_sys_organ ",
            "where ORGAN_OID = #{organOid,jdbcType=VARCHAR}"
    })
    String selectNameByOrganOid(String organOid);
}