package com.zfsoft.microservice.platform.dbaccess.dao.sys;

import com.zfsoft.microservice.platform.dbaccess.data.sys.DbSysPermission;
import com.zfsoft.microservice.platform.dbaccess.data.sys.DbSysPermissionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
@Mapper
public interface DbSysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int countByExample(DbSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int deleteByExample(DbSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int insert(DbSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int insertSelective(DbSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    List<DbSysPermission> selectByExample(DbSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    DbSysPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbSysPermission record, @Param("example") DbSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbSysPermission record, @Param("example") DbSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbSysPermission record);

    /**
     * 获取权限列表
     * @author zxx
     * @date 2020/9/18 1:25 下午
     * @param loginOid 登录人
     * @param appOid 应用
     * @param functionType 类型
     * @return
     */
    List<DbSysPermission> selectByLoginOidAndAppOidAndFunctionType(@Param("loginOid")String loginOid,@Param("appOid")String appOid,@Param("functionType")String functionType);

    /**
     * @description:  根据业务主键查询实体类
     * @param permissionOid 业务主键
     * @author: wuxx
     * @Date: 2020/10/28 9:17
     **/
    DbSysPermission selectByPermissionOid(String permissionOid);

    List<DbSysPermission> selectByPermissionOidList(List<String> permissionOidList);

    /**
     * 根据ROLE_OID查询该角色下是否存在禁用的权限
     *
     * @param roleOid
     * @return int
     * @author ningzz
     * @Date 2020/11/13
     **/
    @Select("select count(*) from t_sys_permission tsp where tsp.IS_DELETE=0 and tsp.IS_ABLE=0 and tsp.PERMISSION_OID in " +
            "(select tsrp.PERMISSION_OID from t_sys_role_permission tsrp where tsrp.ROLE_OID=#{roleOid})")
    int selectNotAblePermissionByRoleOid(String roleOid);

}