package com.zfsoft.single.dbaccess.dao;

import com.zfsoft.single.dbaccess.data.DbSxMaterialElmsConfig;
import com.zfsoft.single.dbaccess.data.DbSxMaterialElmsConfigExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DbSxMaterialElmsConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int countByExample(DbSxMaterialElmsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int deleteByExample(DbSxMaterialElmsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int insert(DbSxMaterialElmsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int insertSelective(DbSxMaterialElmsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    List<DbSxMaterialElmsConfig> selectByExample(DbSxMaterialElmsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    DbSxMaterialElmsConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbSxMaterialElmsConfig record, @Param("example") DbSxMaterialElmsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbSxMaterialElmsConfig record, @Param("example") DbSxMaterialElmsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbSxMaterialElmsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_material_elms_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbSxMaterialElmsConfig record);

    DbSxMaterialElmsConfig selectByMaterialOid(String materialOid);
}