package com.zfsoft.single.dbaccess.dao;

import com.zfsoft.single.dbaccess.data.DbSxServiceRegistrar;
import com.zfsoft.single.dbaccess.data.DbSxServiceRegistrarExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DbSxServiceRegistrarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int countByExample(DbSxServiceRegistrarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int deleteByExample(DbSxServiceRegistrarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long registrarOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int insert(DbSxServiceRegistrar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int insertSelective(DbSxServiceRegistrar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    List<DbSxServiceRegistrar> selectByExample(DbSxServiceRegistrarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    DbSxServiceRegistrar selectByPrimaryKey(Long registrarOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbSxServiceRegistrar record, @Param("example") DbSxServiceRegistrarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbSxServiceRegistrar record, @Param("example") DbSxServiceRegistrarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbSxServiceRegistrar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sx_service_registrar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbSxServiceRegistrar record);

    /**
     * 窗口受理事项列表
     *
     * @author wangwg
     * @date 2020/10/27
     * @param   dbSxServiceRegistrar
     * @return java.util.List<com.zfsoft.dbaccess.data.DbSxServiceRegistrar>
     * @exception
     */
    List<DbSxServiceRegistrar> selectSxServiceRegistrarList(DbSxServiceRegistrar dbSxServiceRegistrar);

    /**
     * 根据授权人员id获取授权事项
     * @param userOid
     * @return
     */
    List<DbSxServiceRegistrar> selectSxServiceRegistrarListByUserOid(String userOid);
    /*
     * @Description:根据事项OID取消授权
     * @Author: wangxl
     * @Date: 2020/12/30 11:40
     * @param serviceOid:
     * @return: int
     **/
    int delSxServiceRegistrarByServiceOid(String serviceOid);

    /**
     * 根据人员OID取消授权
     * @param userOid
     * @return
     */
    int delSxServiceRegistrarByUserOid(String userOid);

    /**
     * 查询所有授权的事项主键
     * @param userOid
     * @return
     */
    List<String> sxServiceOidsListByUserOid(String userOid);

    /**
     * 查询事项是否被授权
     * @param serviceOid
     * @return
     */
    List<String> getServiceRegistrarByServiceOid(String serviceOid);
}
